delegates.md
I'm adding new delegates from yesterday's meeting.  I am also changing all delegates to have 3-letter acronyms, since we are operating separately from TC39.  This means that I added a letter to @zbraniecki and @rxaviers.  Let me know if it look OK.  (This only affects MF-WG, not ECMA-402)
=> Add delegates and update acronyms

guidelines/goals.md
This is based on #59 and the discussion in the March 23rd meeting. The language is sometimes a bit hand-wavy because many details remain to be discussed and decided. If you think I have included to much detail, please let me know.
Let's have another discussion about this in the upcoming monthly meeting next week. I'd like for this list to represent the common agreement of the group with respect to the expectations of the outcome of our work.
[Rendered document.](https://github.com/stasm/message-format-wg/blob/goals-doc/guidelines/goals.md)
=> Goals and non-goals

doc/why_mf_next.md
[Issue #49](https://github.com/unicode-org/message-format-wg/issues/49)
In preparation for the group meeting.
=> Why `MessageFormat` needs a successor

meetings/task-force/#103-2020-09-28.md, meetings/task-force/#103-2020-10-26.md
These are the Markdown formatted notes for issue #103 task force meetings 2 and 3, in the same format as meeting 1's markdown formatted notes in the repo.
To see the files from the PR branch rendered:
https://github.com/echeran/message-format-wg/blob/task-force-103-notes/meetings/task-force/%23103-2020-09-28.md
https://github.com/echeran/message-format-wg/blob/task-force-103-notes/meetings/task-force/%23103-2020-10-26.md
=> add meeting notes for other task force meetings for issue #103

docs/consensus_decisions.md
Resolves #103, resolves #127, resolves #137
As discussed in recent meetings, we have reached consensus on a number of issues, and this ought to be well documented and made more explicit. This PR adds a new document, `docs/consensus_decisions.md`, which enumerates said decisions, along with some clarifying discussion.
The first two were originally documented in the minutes of the [third meeting of the #103 taskforce](https://github.com/unicode-org/message-format-wg/blob/master/meetings/task-force/%23103-2020-10-26.md) and were approved at the [November meeting](https://github.com/unicode-org/message-format-wg/blob/master/meetings/2020/notes-2020-11-16.md) of the workgroup, while the last four are from the discussion on issue #137 (where "3" and "4" are referred to as "1" and "2"), and were …
=> Add consensus decisions

LICENSE
While working on #167, I noticed that this repository does not appear to provide any license for using any of its contents. This is required in order to be able to properly work with the test suite and any other data.
This was briefly discussed during the [2019 Dec 16 meeting](https://github.com/unicode-org/message-format-wg/blob/6b167e1/meetings/2019/notes-2019-12-16.md#process) by @srl295 and @sffc, from which I understand that the intent is to publish everything under the [Unicode License](http://www.unicode.org/faq/unicode_license.html).
This PR adds a `LICENSE` file to the repo root that clarifies this intent to already apply to its current contents. Note that its first paragraph is custom text, as our test suite and other parts have not yet been published in the places defined in …
=> Clarify license for this repository

experiments/stasm/third/README.md, experiments/stasm/third/example/example_glossary.ts, experiments/stasm/third/example/example_list.ts, experiments/stasm/third/example/example_number.ts, experiments/stasm/third/example/example_opaque.ts, experiments/stasm/third/example/example_phrases.ts, experiments/stasm/third/impl/intl.d.ts, experiments/stasm/third/impl/registry.ts, experiments/stasm/third/impl/runtime.ts, experiments/stasm/third/package.json
This is a prototype implementation of the `formatToParts` iterator discussed in #41. The approach taken is the one from https://github.com/unicode-org/message-format-wg/issues/41#issuecomment-900198029 by @eemeli with one modification:
- the iterator yields a flat sequence of _parts_,
- a _part_ can either be a  `FormattedPart {type: string, value: string}` or an `OpaquePart`,
- `FormattedPart` doesn't have the `source` field carrying the original raw value; it was easier to do it that way but also it's consistent with existing `formatToParts` specifications,
- patterns coming from message references are flattened into the final sequence.
Examples:
```
let payloadSize = 1.23;
"Transferred {NUMBER $payloadSize STYLE unit UNIT megabyte}."
{ type: 'literal', value: 'Transferred ' },
{ type: …
```
=> (third) Implement formatToParts

spec.md
As a follow-on to discussion #191, this PR adds a bare-bones outline for us to start filling out with the MessageFormat 2.0 specification text.
The document includes an initial "Meta" section that specifies how additions and changes to the document may be proposed and accepted, along with a conflict resolution process. As it makes clear at its start:
> This document is the incomplete working draft of the MF2 specification. It _will_ experience breaking changes, and should not be depended on by anyone for anything. For now, there isn't even an expectation for various parts of the spec to be in agreement with each other.
The process by which the document may develop is intended to itself develop as we advance with this work. Its initial parameters are entirely adjustable or even replaceable …
=> Add specification text outline

spec/message.ebnf, spec/syntax.md
See https://github.com/unicode-org/message-format-wg/issues/248#issuecomment-1136990557.
=> Use "placeholder" consistently; remove mentions of "placeable".

spec/message.ebnf, spec/syntax.md
Closes #263 by replacing `"quotes"` with `(parentheses)` as delimiters for literal values. Correspondingly, the String token is renamed as Literal, though it's still expected to always be parsed into the data model as a string value.
Within a Literal, both `(` and `)` require escaping. Strictly this is only required for the closing parenthesis, but not also escaping the start looks odd, and should improve the experience for anyone looking at MF2 source in an editor that uses generic parenthesis-matching highlighting.
=> Use (parentheses) rather than "quotes" around literal values

spec/message.ebnf, spec/syntax.md
Adds explicit mention of cases that are often overlooked.
Ref #268
=> Clarify the absolute nature of "any code point"

spec/message.ebnf, spec/syntax.md
As discussed in #269 and elsewhere, it would be beneficial for all placeholder content to start with some sigil or indicator. For markup, the current draft has used `{b}foo{/b}`; that's changes by this PR to `{+b}foo{-b}`.
It's also intentional that this more clearly uses a style that's different from HTML and XML, in order to help close #238.
=> Add +start and -end sigils for markup elements

spec/message.ebnf, spec/syntax.md
- Closes #252
- Closes #253
- Closes #256
- Closes #275
- Closes #286
This proposal goes all-in on considering MF2 syntax as "code", and adds three keywords. As something of a side effect, this requires dropping the `Plain` construction.
Used to define the value of a local variable:
```
let $countInt = {$count :number maximumFractionDigits=0}
```
The syntax here is the same as previously in the preamble, with the addition of the `let`. The keyword is not strictly speaking necessary, but makes it easier to see that an assignment is taking place.
Defines the selectors for a multivariant message:
```
match {$countInt} {$user :gender}
```
Using `match` aligns with other pattern matching syntaxes, which more closely than `switch` maps to what we're doing in particular when selecting with more …
=> Use keywords in syntax

spec/message.ebnf, spec/syntax.md
Surrogate code units (U+D800 through U+DBFF) cannot be encoded into UTF-8.
Ref #268
This covers the most important part of #268, which is UTF-8 compatibility. I would also like to prohibit permanently reserved-for-Unicode-internal-use noncharacters (U+FDD0 through U+FDEF and U+<i>n</i>FFFE and U+<i>n</i>FFFF where <i>n</i> is 0x0 through 0x10, two of which are also invalid XML characters) and control characters (U+0000 through U+001F and U+007F through U+009F, the first 32 of which are not valid unescaped inside a JSON string or [with specific exceptions allowing tab, line feed, and carriage return] in XML), although those can be addressed in a followup (and any of them that should be allowed in string _contents_ will need a corresponding escape sequence, similar to how `\\` represents a …
=> Prohibit surrogate code units

README.md
It was confusing to me, when I tried to read about MessageFormat, what the current state of progress was. This PR links to that from the README.
=> Link to draft syntax from README

README.md
With the merge from `develop` to `main`, the README should link to the syntax in the latter.
=> Fix syntax link in README

spec/formatting.md
As we're discussing the MF2 formatting behaviour, it'd be good if we could start codifying it as well.
This PR adds an essentially empty document `spec/formatting.md` that's marked as a "WIP DRAFT" for this purpose.
Later PRs may then add sections to this that'll let us close issues on which we've reached agreement.
=> Add WIP draft document defining formatting behaviour

.github/ISSUE_TEMPLATE/config.yml
As discussed during today's call, I've added a "Feedback" category to the discussions here: https://github.com/unicode-org/message-format-wg/discussions/categories/feedback
This PR adds a link to that URL to this repo's "New issue" page as a third button: https://github.com/unicode-org/message-format-wg/issues/new/choose
=> Add Feedback discussion category link to issue template selector

README.md
I'd like to improve the README so that:
* It tells a better story of what MessageFormat is.
* It showcases a few examples of the draft syntax.
* It points to the existing tech preview implementations.
* It redirects users who want to share feedback to appropriate forums.
=> Update README with examples and links to feedback collection

guidelines/decision-process.md
As discussed during today's call, we should have a way of fast-tracking some PRs without plenary review, such as minor editorial changes. This adds a section to that effect, copying it almost directly from the [OpenJS Foundation CPC](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#fast-tracking-prs), where it's been used for a while to rather good effect.
When merging this PR, the `fast-track` label should also be added.
=> Add section on fast-tracking PRs to our decision process

guidelines/decision-process.md
Replaces `blacklist` with `proscribe`.
Rationale: Many companies and organizations are working to ensure that non-inclusive language is removed from their repos. For example, changing "master" to "main". The term `blacklist` is one of the ones that is commonly replaced. I am suggesting "proscribe"/"proscription" here as the usual replacement ("disallow") is more appropriate for data values and feels weaker.
=> Use inclusive language

spec/formatting.md
Closes #45
As discussed in the issue and WG calls, it's important for the spec to provide a solid description of its error handling and ensure that the potential of message formatting causing fatal errors is minimised. It's also important for us to strike an appropriate balance with respect to implementation requirements and complexity, and not through this make it significantly more difficult or impossible to put together a compliant implementation.
This error handling spec does not enforce the shape of the errors or the manner of their emission, as long as it does not preclude that _some_ representation of the formatted message is always provided. The text here is rather explicit about the fallback shape of errors when formatting to a string target; that should guide but not restrict …
=> Add error handling

spec/message.ebnf
DBFF is only the high surrogates...
I probably would have done this rule differently, but I noticed the typo just now and can fast-fix it.
=> Actually omit surrogate code points

guidelines/goals.md
Addresses #336
We agreed that we need implementations to demonstrate success. The original non-goal 4 said we would not create implementations. Technically this is true--the MFWG is not creating them, implementers are. However, hewing to the gold standard of "rough consensus and running code", we recognize the need for implementations to exist. To address this, I made a new deliverable 6 defining the need for (but not the direct WG production of) interoperable implementations.
In addition, I did some light editing throughout. Notably:
- defined "dynamic message string", as "localizable message string" is a more expansive definition actually beyond our scope (static messages are out of scope)
=> Rephrase non-goal 4 (Action #336)

README.md
Adds a link in the root Readme to the [ICU User Guide page on MessageFormat 2.0](https://unicode-org.github.io/icu/userguide/format_parse/messages/mf2.html) talking about the ICU4J technical preview implementation there.
=> Update Readme with link to ICU User Guide on MessageFormat 2.0

spec/syntax.md
This is a follow up to #339, which made the same change to the BNF.
=> Omit high surrogates in the prose of syntax.md

spec/syntax.md
To match common use in markdown.
Also correct one remaining use of `(quotes)` instead of `|quotes|`.
=> Use _underline_ for italics in syntax.md

spec/formatting.md, spec/message.abnf, spec/syntax.md
This is a minimally opinionated extension of our `{$foo :bar opt=42}` placeholder syntax to support markup elements.
The idea here is to drop "markup" as an explicit concept in the syntax and to allow for three different function prefix sigils:
- `:` for standalone content
- `+` for starting or opening elements
- `-` for ending or closing elements
The exact meaning of these standalone/open/close concepts is left undefined, allowing for each of the following styles to be equivalently expressible:
```
{Click {|a| +html}here{|a| -html} to continue}
```
```
{Click {+html.a}here{-html.a} to continue}
```
```
{Click {+ph}<a>{-ph}here{+ph}</a>{-ph} to continue}
```
=> Drop separate syntax constructs for markup

spec/message.abnf, spec/syntax.md
The current definition of the `nmtoken` production doesn't match the XML's one. The same is true of `name`, but names are less of an issue. `nmtokens` are frequently used in LDML to define attribute values which are likely to be used a variant keys and option values.
This was originally spotted by @mihnita in https://github.com/unicode-org/message-format-wg/pull/364#issuecomment-1465029138. I [suggested](https://github.com/unicode-org/message-format-wg/pull/364#issuecomment-1465033819) fixing it in one of the two following manners:
> * by adding `:` only to `name-char` (and thus, to `nmtoken`), and accepting that `name` is not the same as XML's `Name` but at least `nmtoken` is aligned, or
> * by adding `:` to `name-start`, aligning both `name` and `nmtoken` with their counterparts in XML. …
=> Allow colons in nmtokens

spec/formatting.md
This is an attempt to explicitly document how case/variant selection happens with messages that have a `when` selector statement. The method presented here implements the "column-first" selection method that was agreed upon at the last meeting.
A JS implementation of the algorithm is available; see #369 for more information on that.
The overall intent is to minimally but sufficiently define selection, such that two implementations that use similar custom selector functions will make the same selection, when given the same input message and formatting context. In a number of places details are left for each implementation to fill in for themselves, as each may have a different internal representations of resolved and unresolved values and may perform value matching in different ways.
By …
=> Add column-first pattern selection

spec/formatting.md
This is in part a follow-up from this conversation with @aphillips: https://github.com/unicode-org/message-format-wg/pull/364#discussion_r1190848443
The intent here is to be clear and explicit about the meaning of literal values. While putting this together, I started to think that we might need yet another section discussing other treatment of message parts than formatting. For instance, I understand us to be aligned with expecting literal values to by default be presented as non-translatable. It would be good to note this somewhere, but "formatting" isn't really the right place for it.
=> Add Literal Resolution section to formatting.md

spec/formatting.md
* State up front that the catch-all key `*` is never passed to the implementation-defined key-comparison method
* Clarify the relationship between selector length and key length
* Clarify the type signature for `SortVariants`
* Fix typo
=> Clarifications to pattern selection

spec/formatting.md, spec/message.abnf, spec/syntax.md
Currently, a valid `nmtoken` like `42` or `foo` can be used directly as an option value `key=42 bar=foo`, but needs to be quoted when used as an argument: `{|42| :number|`, `{|foo|}`. This is a bit of a wtf, and there should be no need for this difference.
This is a relic from when the syntax considered a placeholder with just an `nmtoken` to be a markup-start, but this was changed in #283. This PR allows for all `nmtoken` excpet for ones starting with a `-` to be used as an expression argument.
=> Replace `nmtoken` with `unquoted`

spec/README.md, spec/formatting.md, spec/registry.md, spec/syntax.md
This fixes the following editorial issues in the spec:
- Always style normative key words using all caps: MUST, MAY, etc.
- Always use **_definition_** and _reference_ styles
- Always use `>` block quotes for examples
- Always use semantic line breaks
- Apply Prettier markdown styling
- Update ToC in readme
=> Harmonise spec style

spec/formatting.md
In PR #385 from @catamorphism  I made the [comment](https://github.com/unicode-org/message-format-wg/pull/385#discussion_r1211860808) which suggested a different approach to pattern selection. This PR addresses that comment.
=> Change the "pattern selection" text

docs/archive/markup-support.md
On visiting the WG, I was (am) deeply interested in ultimately ensuring the `formatToParts` like implementation became part of the spec. I did not understand...
- the prior context for which all discussions on the matter had occurred in
- what different team members meant when using the term "markup" in context of this repo
- the state of markup support in MFv2 (i'd argue, few _actually_ have a great grip on this, outside of a select few, having read all of the issues 😄 )
Read through the rich history of markup in the codebase. Capture,
- each key discussion
- interesting takeaways from the discussion
- a "Status", representing the sentiment that I perceive that the WG wants from "markup" support
=> docs: markup feature history

docs/glossary-and-resources.md
["roundtrip" is used liberally](https://github.com/search?q=repo%3Aunicode-org%2Fmessage-format-wg+roundtrip&type=code) in captured documentation, but has no captured definition in the glossary
Define the term
=> docs: add roundtrip to glossary

spec/formatting.md
This is still incomplete and will need plenty of additional work, but I thought I'd share at least the current shape of my thoughts.
@aphillips You mentioned being able to potentially help out a bit with this? It's missing at least some description of what actually goes on in formatting a resolved pattern, but what else do we need to include? The bidi stuff is explicitly left out here, as that's progressing in its own PR.
=> Add missing formatting sections

spec/formatting.md
This cleans up a few things that were not included in PR #396. Namely:
- A formatting context suggestion from @aphillips.
- Avoid using non-normative "may".
- Add resolution rules for private reserved annotations.
=> Fix normative vs. non-normative keywords in formatting.md

spec/formatting.md, spec/syntax.md
See #425 for context.
Adds this requirement to the spec, and a corresponding data model error:
```markdown
Each _selector_ MUST have an _annotation_,
or contain a _variable_ that directly or indirectly references a _declaration_ with an _annotation_.
```
Edit: Added "directly or indirectly" to the original proposal, to account for messages like:
```
let $one = {|The one| :func}
let $two = {$one}
match {$two}
when 1 {Value is one}
when * {Value is not one}
```
=> Add Missing Selector Annotation error

spec/syntax.md
This includes fixing the style of **_definitions_** and their _references_.
In the course of doing this change, I made some non-editorial changes:
* Introduce terms and definitions to clarify _selectors_, _match statement_, and _selector_ and concepts. Our text was difficult to read because there was no way to refer to the `match` clearly (because the production is called `selectors`) or to refer to a specific _selector_ (or just the selector expressions minus the keyword `match`). Hopefully this is a step in the right direction. This transformation is incomplete, since there are several places that refer to `match` rather than _match statement_, etc.
* I split `private-use` from `reserved`, although that really should be a separate PR.
* I modified the structure and description of the …
=> Styling and structure changes to syntax.md

spec/README.md
Addresses #416
This commit is the first of several to address styling and formatting consistency issues in the specification.
* The 2119 keywords paragraph now quotes RFC 8174 verbatim.
=> Fix styling to be consistent

spec/message.abnf, spec/syntax.md
This was missed in #364, which was introduced before but merged after #374. Previously included in #414.
`reserved-body` needs to allow for `quoted` values (which were named `literal` at the time of its writing) to support expressions like
```
{^foo |some {text} here|}
```
as the `{}` within the `|` quotes does not need to be escaped.
As is, the ABNF is a bit broken for `reserved-body` as there are characters that are valid as either `reserved-char` or `literal`.
=> Fix `reserved-body` to use `quoted` rather than `literal`

spec/data-model.md
At the moment, the data model includes a boolean `quoted` property on the `Literal` construct. This should be dropped, as it's not meant to effect anything during the runtime.
As the data model is extensible by implementations, this does allow for an implementation to add the field back in as a private extension, should it have a need to track this information.
=> Drop the Literal quoted flag from the data model

spec/syntax.md
This is the second attempt at the specification refactoring. I started with all of our PRs merged Monday.
This is a much more significant reformulation. It is intended to be read as prose as well as specifying individual productions. 
I organized the sections "top down", with some sub-sections containing others, e.g.:
> # Message
> ## Declarations
> ## Body
> ### Pattern
> ### Matcher
> #### Selector
> #### Variant
> ##### Key
There is then a set of productions about Expressions and then finally the remaining terms, such as keywords, whitespace, and such. You might wish to view this rendered first rather than diving into the diff specifically.
---
I have followed commentary about separating "abstract" vs. "concrete" (e.g. in #440). This proposal embraces the use of ABNF constructs whose …
=> Specification refactor "v2"

spec/data-model.md, spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json
The data model `Reserved` interface may also be used for private-use annotations that are not supported by the implementation. This PR adds text clarifying that to be the case, and explicitly mentions that private-use syntax that is supported by the implementation may use a different interface.
The `source` definition is also corrected to _not_ include the starting sigil. This was the only point in the data model where a part of the syntax was showing up twice, without a really good reason why.
=> Clarify that Reserved may also represent private-use in data model

exploration/0000-design-proposal-template.md
I'd like to suggest a new process for discussing and designing features and changes to MF2: document the design in a single Markdown file before implementing it *in the spec*.
Today, the scope and the specification of MF2 are concrete enough to be a good base against which incremental designs can be evaluated. MF2 is also complex enough to require a good deal of consideration of how a newly introduced change interacts with other parts of the standard.
In particular, I think such documents would be the right place to gather use-cases and requirements in a way that (a) allows us to evaluate alternative designs, and (b) can be looked up in the future to understand what problem we wanted to solve.
New proposals would be made in form of PRs adding a new file to the `exploration` directory. …
=> New process: design proposal template

.github/workflows/prettier.yaml
It turns out that our `main` branch is in fact protected, and that the action can't write to it.
So rather than trying to fix the styles everywhere, this limits the action to just `docs/`, `exploration/` and `spec/`.
It should also now run for `pull_request` events, in case a PR is made from a fork that isn't allowing actions.
=> Limit Prettier action to selected directories & events

.github/workflows/prettier.yaml, .gitignore, package.json
This shouldn't be as hard as it appears to be, but alas.
In forks where it's allowed to run, the action should still "just work".
For PRs coming from branches in this repo, the `ref` is now set so that the `git push` should "just work".
For PRs coming from branches in forks, it doesn't look like there's a way to get the action to have sufficient access so that it can write to that branch from the target repo, even if a human user could. So for those cases, the explicit `repository` is set and the action will only fail on `git push` if there are any files that Prettier should be run on.
In other words, the action should now work as a CI check when it's not able to automatically fix things.
A `package.json` is added, so that `npm install && npm run prettier` can be run locally to apply the …
=> More Prettier action fixing

exploration/0000-design-proposal-template.md
We should track and signal the status of a design document, so that we can iterate on them across multiple PRs. To keep it simple, we probably don't need more than two statuses to start with, "proposed" and "accepted".
CC @ryzokuken, who also has a design doc PR in flight.
=> Add proposed/accepted status to design docs

exploration/0002-expression-attributes.md
As discussed on the past two calls. A preview of the doc is available [here](https://github.com/eemeli/message-format-wg/blob/expression-attributes-design/exploration/0002-expression-attributes.md).
See also #450 for a possible implementation of the proposed design.
=> Add design doc for expression attributes

spec/formatting.md
Fixes #42 
Also addresses some problems with normative terms in the same text.
=> Allow expressions without annotations to dynamically choose a function

spec/formatting.md
Adds normative note stating that this specification doesn't require either eager nor lazy evaluation.
=> Clarify eager vs. lazy evaluation

spec/README.md
As discussed face-to-face yesterday.
The first two paragraphs state that future changes won't break your old MF2 messages, and that future messages will not use syntax that an older parser will consider as errors -- this is why we've _reserved_ some parts of the spec.
The last paragraph is about soft-reserving namespace for future spec versions.
=> Add stability policy

spec/README.md
When #472 was merged, it ended up including changes suggested by @aphillips in https://github.com/unicode-org/message-format-wg/pull/472#discussion_r1327996351 that had not been fully reviewed. This PR is about fixing issues related to that late addition.
Right now this is mostly editorial, and re-introducing a phrase that was dropped on merge:
> Later specification versions MAY make previously invalid messages valid.
However, we should also decide here what to do about this indented note that was included in the change:
> > Note: future versions may define new keywords.
For this to be valid, we need to find a way to make it play nice with this other bit of policy:
> Updates to this specification will not introduce message syntax that,
> when parsed according to earlier versions of this …
=> Fix stability policy

exploration/variable-mutability.md
Per today's call (2023-09-04) here is the start of the design doc to address the need to decide how to handle:
- variable mutability
- local vs. external variable "masking"
This is based in large part on the discussion in #310 coupled with some discussion elsewhere. I incorporated commentary liberally. 
The design presented here is for limited mutability (only via a separate keyword) and for separate namespaces.
_Let the games begin._
=> Design document for variable mutability and namespacing

exploration/pattern-exterior-whitespace.md
This PR cleans up some of the details of the whitespace design document in anticipation of the need to revisit it in an upcoming teleconference.
Changes include:
- formally define `pattern exterior whitespace`
- syntax highlight some terminology using our convention
- Added a section about non-`s`-production whitespace explaining it's impact on enclosed pattern "exterior" whitespace
=> Cleaning up whitespace design

exploration/text-vs-code.md, spec/syntax.md
An update to the design doc, specifically on the topic of: "Do we allow unquoted variant patterns?"
Very much a WIP while in draft mode (not suitable for "drive-by reviews" until officially ready for review).
@mihnita please take an initial look and provide suggestions.
=> Update design doc for message pattern quoting

exploration/delimiting-variant-patterns.md
- Rename the design doc.
- Cross out rejected options 2 and 5
- Add notes to 2 and 5 calling this out
(other changes may be added from the previous thread in #503 and WG call notes from 2023-10-30)
=> Prepare design doc ahead of balloting

spec/formatting.md, spec/syntax.md
Having reviewed @catamorphism's previous text and looking at our current text, these are proposed **_editorial_** changes to make variable immutability clearer in the spec. The previous text's "a _messages_ is not considered valid" doesn't read as proper English. We also lack an error for this (we have one for duplicate options), so I added one.
=> Clarify declaration immutability

exploration/open-close-expressions.md
My goal is, as usual, to avoid adding new sigils to the syntax. Instead, I’d like to leverage the fact that we already have the concept of keywords in the syntax. Furthermore, with https://github.com/unicode-org/message-format-wg/pull/469, we were able to find a good solution by adding a new keyword (input). I think we can try to do the same here.
This PR is a slightly expanded version of my comment in https://github.com/unicode-org/message-format-wg/pull/470#issuecomment-1795578141.
=> Open/close design: A familiar HTML-like syntax as an alternative

exploration/overriding-extending-namespacing.md
Per a comment from @stasm, saving a user story from a [comment in #524](https://github.com/unicode-org/message-format-wg/pull/524#discussion_r1394423131) into the design doc.
=> Copy user story from #524 to design doc

spec/registry.dtd
This is a purely editorial change, so asking for fast-tracking.
This makes the `registry.dtd` align with commonly used conventions on its formatting.
=> Reformat `registry.dtd` to not repeat `<!ATTLIST>` & align attribute definitions

exploration/open-close-expressions.md
This reflects the consensus reached during the 2023-11-20 call, to accept `{#foo}...{/foo}` as the open-close syntax.
The previously proposed `{#foo/}` syntax for standalone elements did not reach consensus, and so is left out here.
Examples are updated to use the new syntax, and the `{+foo}...{-foo}` alternative is documented as such.
=> Update open-close design doc to accept the hash & slash alternative

spec/formatting.md, spec/message.abnf, spec/syntax.md
Initial implementation of namespacing design into the spec.
This version makes the following pair of options parallel to one another (i.e. they are not duplicates):
```
{$foo :function option=value ns:option=value2}
```
=> Implementing namespacing

spec/message.abnf
This starts implementing the changes for the [code mode introducer](https://github.com/unicode-org/message-format-wg/blob/main/exploration/code-mode-introducer.md) (#521, #526), including dropping `when`.
Before I get any further, it might be best for us to align on the exact ABNF changes. See line comments for a few specific questions.
=> Implement code more introducer

exploration/open-close-placeholders.md
I noticed that the open-close design doc was in places (like its title...) talking about _expressions_ when it's really about _placeholders_. In our current syntax, those are synonymous, but the change we're proposing here would make them different, and while _markup_ would be a _placeholder_, it would not be an _expression_.
Requesting fast-tracking, as we're currently discussing this in #537.
=> Clarify that open-close elements are placeholders, not expressions

spec/registry.dtd, spec/registry.md, spec/registry.xml
Adds `<alias>` definitions to the registry, so that shorthands like `:integer` can be made available.
=> Define function aliases in registry, initially including `:integer`

spec/registry.dtd, spec/registry.md
Closes #410 
At the moment, locale-specific overrides work via the `locales` attribute list of identifiers on `<formatSignature>` and `<matchSignature>`. This is a bit clumsy, because it's mixing together two different concerns:
1. Some functions may have options that are only available in specific locales.
2. Some selectors may have their matching depend on the locale.
So I propose separating the two. Let's remove the `locales` attribute from the signatures, and rather:
1. Allow for a `<override locales="...">` within a signature that may include rules for inputs and options that override any set generally for the formatter.
2. Allow for both `<match>` and `<match locales="...">`, and specify that only one such rule (first matching one) is used at a time.
This should make it easier to …
=> Refactor registry locale overrides

spec/message.abnf, spec/syntax.md
Implements the changes discussed in the 2023-12-04 teleconference.
This makes an unquoted literal be a name or a number.
This PR does **NOT** include changes to `+` and `-` sigils in the `function` production pending discussion/implementation of hash-and-slash for spannables. Merging this PR without those changes will make our syntax inconsistent/ambiguous.
Fixes #518 #519
=> Unquoted literals as name or number

spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json, spec/message.abnf, spec/syntax.md
More accurately captures annotations in the data model, particularly when they are unsupported, and also just generally increases alignment between data model representations and the ABNF.
Fixes #552
=> data-model: Better represent annotations in the data model, particularly when unsupported

exploration/open-close-expressions.md, exploration/open-close-placeholders.md
See https://github.com/unicode-org/message-format-wg/pull/535#issuecomment-1831867288.
Right now, the doc recognizes that standalone elements are still an open question, but the documented proposal goes one step further: it suggests to use the registry to encode the standalone aspect.
In this PR, I list all previously suggested alternatives on an equal level, since no decision has been made about them yet.
=> (Design) Document the open questions around standalone markup

spec/formatting.md
A follow-up to https://github.com/unicode-org/message-format-wg/pull/524#discussion_r1409411240:
@stasm:
> I see that this step was added yesterday in a suggestion from @gibson042. What is the purpose of it? Why wouldn't we want functions to see unresolved options?
@eemeli:
> This is a small fix unrelated to namespacing that's bundled in here to ensure that if
> 
> ```
> {:foo opt=$none opt=bar}
> ```
> 
> is formatted with `$none` not resolving, not only will that cause an Unresolved Variable error to be emitted, but that a Duplicate Option Name error will also be emitted -- the latter was previously skipped.
> 
> The behaviour around options with errors is unchanged from the previous; it's just expressed a bit differently. If you think that ought to be changed, then that should go in a …
=> Formatting: Don't remove unresolved options from the map passed to the function

spec/syntax.md
As discovered in https://github.com/unicode-org/message-format-wg/pull/557#discussion_r1428727301, this was added in #431 but accidentally dropped in the #441 refactor.
=> Re-add accidentally dropped message validity condition

spec/registry.md
=> Describe registry use and conformance

exploration/exact-match-selector-options.md
In response to #433 we need to choose a name for the "exact match" selector.
This isn't done yet but will serve as a foundation for choosing.
=> (Design) Exact Match Selector Options

exploration/open-close-expressions.md, exploration/open-close-placeholders.md
This PR updates the design doc to include `{#standalone/}` markup as discussed on today's call, and should reflect the consensus reached during the meeting.
~This is a **draft** PR filed in support of the discussion in #537, and its eventual conclusion of the discussion on spannables/markup. We may want to amend this as an outcome of the discussion, but for now it's here to allow for the collection of the various historical issues that we'll be able to resolve with this.~
~You are not expected to review this PR until we've settled on the matter in #537.~
Closes #240 
Closes #262
Closes #375
Closes #424 
Closes #537
=> Accept open-close design doc

spec/README.md
@macchiati [suggested](https://github.com/unicode-org/message-format-wg/pull/571#issuecomment-1861926877) we remove the additional text beyond the non-operation of the stability policy.
=> Remove mention of stability criteria

exploration/default-registry-and-mf1-compatibility.md
Create a list of selectors and formatters required by the default registry as well as a matrix showing how MF1 and MF2 map functionality. 
This is an attempt to capture the current (and proposed) registry entries for the spring release. If we're missing something, it needs to get added.
🎵 _...he's making a list and checking it twice..._  🎵
=> (Design) Default registry and MF1 compatibility matrix

spec/data-model/README.md, spec/data-model/message.json
Feedback from writing the JS implementation:
In the data model, the wrapping object in the `Pattern` which has a single `body` property is rather useless. We should flatten this to simplify the model a bit.
One reason why the wrapping object was included earlier was to enable an extension of the data model to function as a CST, but in practice I at least found that its requirements are sufficiently different for the CST to work better as a separately defined structure.
This PR overlaps a bit with #574; whichever lands second will need a small adjustment to deconflict the merge.
=> Flatten JSON & TS data model Pattern element

exploration/exact-match-selector-options.md
A follow-up to the [December 18](https://github.com/unicode-org/message-format-wg/blob/main/meetings/2023/notes-2023-12-18.md) meeting: document two more naming alternatives for the default exact match selector.
=> Add :stringified, :enum as alternative in the exact match selector design doc

spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json, spec/formatting.md, spec/message.abnf, spec/syntax.md
This implements markup [as designed](https://github.com/unicode-org/message-format-wg/blob/main/exploration/open-close-placeholders.md), including syntax, data model, and formatting changes.
The open/close/value "kind" concept is removed from functions, which now only ever use `:` as a prefix. The `+` is added to `reserved-annotation-start`, but `-` is not.
Resolution and formatting to a string is defined for markup, but formatting to parts is not, given that we don't define parts.
Noting for @gibson042 in particular: In the data model, I did need to add a `type: "expression"` on the expressions, so that they could be differentiated from the `type: "markup"` elements that a pattern may now also hold.
=> Add markup as designed

spec/data-model/README.md, spec/data-model/message.json
Some of the merge conflicts between #574 and #585 were incorrectly resolved. This fixes them.
This PR should be considered editorial, and preferably fast-tracked.
=> Fix merge of markup PR

spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json, spec/formatting.md, spec/message.abnf, spec/syntax.md
As discussed during this week's call, this adds @attributes to _expression_ and _markup_ with runtime impact.
For the syntax & data model, this is mostly a rebase of #450 that leaves out any discussion of what attributes might be good for, while noting that "_Attributes_ are reserved for use by future specification versions."
For formatting, the language is rather more forbidding:
> _Attributes_ MUST NOT have any impact on message formatting, and MUST NOT be available in the formatted output. _Variables_ in _attribute_ _values_ are not resolved, and no errors are emitted for them.
Closes #453, as using _identifier_ brings in the same namespacing we're using for _options.
This also closes #587, as removing `@` leaves the remaining symbols sorted in code point order.
=> Add @attributes as reserved

spec/formatting.md, spec/syntax.md
I noticed during implementation that even though we define Duplicate Option Name as a data model error, we handle it as a formatting error. This should be clarified.
=> Clarify that Duplicate Option Name is a data model error

spec/appendices.md
Addresses #579 
Adds a document for appendices and populates with with Security Considerations. I considered adding this to the front matter, but observe that most documents place these types of materials at the end.
Please suggest other considerations as needed.
@duerst, please also have a look.
=> Add security considerations section

exploration/exact-match-selector-options.md, spec/registry.xml
This implements the [proposed design](https://github.com/unicode-org/message-format-wg/blob/main/exploration/exact-match-selector-options.md#proposed-design), and marks the design as approved.
=> Add `:string` as formatter and selector

spec/registry.xml
As discussed in https://github.com/unicode-org/message-format-wg/pull/570#discussion_r1452487765, the `hourCycle` option is also valid when using the `timeStyle` or `dateStyle` options of `:datetime`.
I suggest this is considered as an editorial change and fast-tracked.
=> Add missing hourCycle to :datetime timeStyle/dateStyle <formatSignature>

spec/message.abnf, spec/syntax.md
This change does not change the syntax in any way, and only introduces a `content-char` rule as a common base for other character classes.
At the moment, we have multiple explicit character range definitions in the ABNF, and it's not easy to see that they are very nearly the same as each other, and how exactly they differ. By introducing their overlap as `content-char`, this becomes more obvious to a reader.
=> Add content-char as common root of simple-start-char, text-char, quoted-char & reserved-char

spec/formatting.md
Addresses #549 
- Formally names the bidi isolation strategy as "Plain Text Bidirectional Isolation Strategy". 
- Refactors some text, fixing some problems with referring to bidi.
- Adds a better example from `ar-AE` locale
The algorithm isn't quite right yet.
=> Improve bidi isolation requirements

exploration/default-registry-and-mf1-compatibility.md
In the 2024-01-15 call we agree that the functions listed in this document are the comprehensive set for the `LDML45` default registry. This updates our documentation to reflect that.
The list of options, operands, etc. remain open for discussion, but no other functions will be considered.
=> Update default registry design doc to reflect LDML45 scope

spec/formatting.md
Addresses #590
Replaces the amorphous term "shape" in Formatting with more appropriate text. Generally I used a reformulation using some variation of the word "form".
In one case, I deleted the paragraph. The paragraph in question was non-normative and basically said the same thing as a normative paragraph just below it--that how formatting works is implementation-defined.
---
In fixing this, I corrected one typo.
I also transformed the eager/lazy note into an "IMPORTANT" (which also restores it's intended normativity)
=> Replace 'shape' with better terminology

spec/message.abnf
The `0` here was evidently meant to represent a literal character 0, but as I understand ABNF this would be interpreted as a counter modifier for a later item. It would be quoted as a string `"0"`, but the later range `[0-9]` is not quite so easy. To be a range one kind of needs to specify the actual character codes (as is done elsewhere in this very grammar). I encoded the zero as `%x30` and the range one-to-nine as `%x31-39` so all the literal digits are represented the same way.
=> Correct bogus ABNF syntax matching literal numbers

exploration/builtin-registry-capabilities.md
The [Capabilities for built-in registry](https://github.com/unicode-org/message-format-wg/blob/main/exploration/builtin-registry-capabilities.md) design doc by @ryzokuken was one of our first, but it's rather languished in obscurity since, and has been somewhat overtaken by the already-accepted [Default Registry and MF1 Compatibility](https://github.com/unicode-org/message-format-wg/blob/main/exploration/default-registry-and-mf1-compatibility.md).
We should note that the earlier proposal has effectively been accepted, while also updating its list of supported capabilities to match our current considerations, in particular dropping list formatting from the initial release.
=> Accept proposal on built-in registry capabilities

spec/registry.xml
This implements the [number selection design](https://github.com/unicode-org/message-format-wg/blob/main/exploration/number-selection.md).
Separately from this, we should add a "default functions" section to `registry.md`.
The only `<match>` included in this proposal is the fallback one; further changes could follow if/once #558 is accepted.
=> Add a `<matchSignature>` for `:number`, together with `:ordinal` & `:plural` aliases

exploration/default-registry-and-mf1-compatibility.md
The important part here is dropping the `{$num :percent}` and `{$num :currency}` examples, but while at it I added some `:date` and `:time` examples and tried to also otherwise prettify it.
Also added `.match {$num :number select=exact}` as a solution for some MF1 `select` usage.
=> Clean up MF1 compatibility matrix

exploration/default-registry-and-mf1-compatibility.md
Based on the 2024-02-05 teleconference discussion, describe the date/time formatting functions in a manner similar to the number selection design document.
Open issues:
- I reference BCP175 and the IANA time zone database. Should we have additional zone IDs supported, such as the BCP47 compatible ones from ULIs?
- We need to choose the supported serialization(s) for date literals. RFC3339, XMLSchema, and JSON all provide some things here. SEDATE's extension to support Temporal should be added when its ready.
=> Describe date/time formatting functions and options

spec/formatting.md
This change clarifies that when an implementation "performs additional processing" on the expression of a declaration, that expression must be a variable with no annotation.
This came up when discussing #589 and is a purely editorial change.
=> Clarify when "additional processing" of a named value occurs

exploration/open-close-placeholders.md
As a follow-up to https://github.com/unicode-org/message-format-wg/pull/541#pullrequestreview-1787622004, we'd like to allow options on "close" markup placeholders.
The main use-case is tooling and XLIFF interchange. See also #450 which proposes a different mechanism for this (but hasn't yet been accepted).
=> Allow options on closing markup placeholders

spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json, spec/formatting.md, spec/message.abnf, spec/syntax.md
=> Add options to close (spec)

spec/README.md
=> Add data model to stability policy

spec/errors.md, spec/formatting.md
This includes the change to formatting.md to match.
=> Address #629: create invalid expression error

spec/data-model/README.md
A follow-up to #620, see the discussion there.
=> Make arrays in the data model not optional

spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json
=> Merge the unsupported-annotation sigil into its source in the data model

exploration/default-registry-and-mf1-compatibility.md
Unaddressed feedback from https://github.com/unicode-org/message-format-wg/pull/648#discussion_r1491319250:
> One of the features of semantic skeleta is preventing nonsensical skeletons like "hours and seconds" without minutes. Mapping from standard skeleta to semantic skeleta may fill in some of those missing fields. Even now, fields such as hour cycle and era may appear even if not in the skeleton. Therefore, it would be better to remove the second sentence giving any guarantees about which fields appear in the formatted output.
=> Reduce strictness of datetime field options

spec/syntax.md
The ABNF has recieved a major overhaul with difrenet formatting, and also along the way several small changes and fixes landed. These changes are not reflected in the relevant snippets in the syntax document.
This brings all the snippets up to date with the actual ABNF. One could easily make a case that the formatting doesn't need to match and each snippet could have its own whitespace choices to match the local context, but it was much easier to find changes and reason about them if the lines exactly matched the ABNF file, so I went ahead and updated all the formatting.
In the process the actual changes showed through. Some changes are typo fixes (e.g. `reserve-escape`→`reserved-escape`), others have more exact definitions (e.g. `reserved-keyword` and `reserved-statement`), and a couple …
=> Port ABNF changes and fomatting to syntax document

exploration/string-selection-formatting.md
Flesh out `:string` using the format we used for dates and numbers.
=> Define `:string`

spec/errors.md, spec/formatting.md, spec/syntax.md
Fixes #569 
Going through our specs to remove or repair examples so that they match the functions in the default registry.
Some generic examples are retained, e.g. `:func` in errors.md where we want to focus the example on syntax rather than the registry.
These changes are strictly editorial. Seeking fast-track for this.
--
Errors.md:
- fix `:number` options to be spelled out correctly
- fix formatting error examples to use real functions
--
Syntax.md:
- Replace multiple selectors example with two numbers. The previous example used a mythical custom function for gender. 
- If the text said it was a _message_, enclose the example in `{{ }}`
- Replace options examples to use `:datetime` options rather than the complicated custom function
=> Remove non-registry functions and options from examples

spec/data-model/message.dtd, spec/data-model/message.json
Fixes #667, CC @bhaible.
This was missed out in #443.
=> Drop "quoted" remnants from JSON Schema & DTD data models

spec/message.abnf, spec/syntax.md
Fixes #670 
`content-char` wants to skip U+0020 (`SPACE`) but manages to skip U+001A through U+001F too...
=> Fix #670: fix `content-char`

spec/data-model/README.md
Per our discussion of #575, we want to say that the field `name` in the data model encompasses the production `identifier` in cases where the name is an identifier.
Fixes #575.
=> Address #575: say that data model uses `name` for `identifier`

spec/formatting.md
Per my action-item, add an appropriate note about the requirement for the fallback variant, including text seeking feedback in tech preview.
Fixes #619
=> Address #619: add a note about `*` variant

spec/syntax.md
Address the [comments](https://github.com/unicode-org/message-format-wg/pull/647#discussion_r1496279913) by @macchiati and @stasm on #647 that came post-merge. Basically this is modifying the informative note about attributes.
=> Address phrasing comment on #647

spec/registry.md
This PR copies the number and date/time default functionality from design to the specification.
The copy was done verbatim, except:
- I moved some parts of number to make the structure logically consistent
- I added an example to the `style=percent` note
- I turned the information about the default selector into an "important" note
- I added the surrounding document structure
=> Implement the default registry in the spec

spec/data-model/message.dtd
Fixes #676
This resolves the naming inconsistency in the data model DTD.
The further recommendation by @bhaible
> Maybe also by changing the `value` in the CatchallKey to `identifier`, and adding an attribute `identifier` to the XML DTD element (instead of overloading the meaning of the XML element's contents).
is not included here, as it would potentially add more confusion. In the MF2 syntax, the non-default variant keys are _literal_ values, rather than _identifiers_, and the data model's catchall `value` is not used when representing MF2 syntax. It's there to support the lossless representation of other syntaxes, which may assign a literal value to their catchall variants.
=> Rename <key default> as <key catchall> in message.dtd

spec/registry.md
This clarifies the status of the registry data model as experimental.
Fixes #683
=> Address #683: make registry data model non-TP

spec/syntax.md
This was discussed on [2024-02-15](https://github.com/unicode-org/message-format-wg/blob/main/meetings/2024/notes-2024-02-15.md#topic-registry-maintenance), and is mentioned in the #634 design doc.
=> Reserve the "u" namespace

spec/registry.md
Per 2024-02-26 teleconference, add a note about the value `2-digit`
=> Note the need to quote `2-digit`

spec/syntax.md
The working group discussed accepting #673 for the tech preview. Because this was a late-breaking change, the group decided to work on incorporating work on bidi and UAX31 conformance in the early post-45 period.
I was tasked with creating a PR with a note about bidi for the Tech Preview specifically. This note is adapted from text proposed in #673.
It also fixes two formatting errors for notes in the syntax doc.
=> Add note about bidi for Tech Preview period

spec/message.abnf, spec/syntax.md
Closes #669
As @bhaible points out, U+0000 NUL characters are challenging in null-terminated strings as well as XML. These are real concerns, but U+0000 should still be representable in MF2. Rather than requiring custom solutions that are likely to not be mutually compatible, we should make a specific affordance for U+0000, removing it from `content-char` and adding `\0` as an MF2 escape.
=> Do not allow null characters in message source

spec/data-model/README.md
See #669, CC @bhaible
I agree with @aphillips that we should not restrict `content-char` characters because they're not all representable in XML. But we should explicitly note to readers that there is a concern here, and that they may need to add restrictions for their own message validation if they rely on XML.
=> Add note about XML C0 characters adding restrictions

spec/formatting.md
Currently, the introduction to the spec states:
>   The form of the resolved value is implementation defined and the
>  value might not be evaluated or formatted yet.
> However, it needs to be "formattable", i.e. it contains everything required
> by the eventual formatting.
And the "Expression and Markup Resolution" section says:
> Since a _variable_ can be referenced in different ways later,
> implementations SHOULD NOT immediately fully format the value for output.
However, the "Function Resolution" section is not as clear as it could be about the implications of these requirements for the interface with formatting functions.
I added some text that effectively implies that functions have the same operand type and result type. If this wasn't the case, it wouldn't make sense to bind the …
=> Add note to "Function Resolution" section about function argument and result types

spec/formatting.md
One of the notes in yesterday's merge was formatted incorrectly. This one character fix restores proper formatting.
=> Fix formatting of a note

README.md
This includes a short paragraph under "What is MessageFormat 2?" whose purpose is to satisfy #693 (the need for a v45 "intro paragraph")
=> Prepare front-door for Tech Preview

spec/data-model/message.json
Fixes #698, CC @bhaible
This was missed in #574.
=> Drop obsolete mention of "kind" in function-annotation JSON Schema definition

README.md
This PR is for updating our front-door as we get to the TP release.
I would like to merge it close to the LDML45 freeze.
Changes:
- I drew an action in the 2024-02-26 call related to #673 to add a note about UAX31 bidi handling. We'll list normative changes as we fix them.
- Started to update the "implementations" section.
=> Further front-door prep

test/test-functions.json
These tests may be able to be re-added after resolving https://github.com/unicode-org/message-format-wg/issues/675
=> Remove tests that require non-integer matching

spec/formatting.md
As noted in https://github.com/unicode-org/message-format-wg/pull/704#pullrequestreview-1921417562, this was already fixed once in #577, but mistakenly reverted in the merge of #593.
=> Clarify (again) that Duplicate Option Name is a data model error

spec/message.abnf, spec/syntax.md
In all places where a 'reserved-body' can occur:
- in a reserved-statement,
- after a reserved-annotation or private-use-annotation, in a literal-expression, variable-expression, or annotation-expression, it can be followed by whitespace ('s' nonterminal).
A syntax ambiguity exists, because - as reported in #721 and #725 - a U+3000 character can occur as the last character of a 'reserved-body' (via a 'reserved-char') and also as first character of whitespace ('s' nonterminal).
According to the principles explained in #725, it is not desired that a 'reserved-body' ends with a U+3000 character; rather, the U+3000 character is meant to be interpreted as part of the following whitespace.
Test cases (written with \u escapes, for legibility): For reserved-statement:
.regex …
=> Disallow U+3000 as the last character of a reserved-body.

test/test-functions.json
I'm presuming that `RangeError` is supposed to be `bad-input`.
In general #706 is still needed: e.g. it's not clear that `bad-input` refers to an ["Operand Mismatch Error"](https://github.com/unicode-org/message-format-wg/blob/main/spec/errors.md#invalid-expression), but I'm assuming so. For now, this PR just tries to make the test suite internally consistent.
=> Remove references to "RangeError" in spec tests

spec/errors.md
This example is now a syntax error, because of attributes. Changed to an example that would be an "unsupported expression" error.
=> Fix "unsupported expression" example

spec/message.abnf, spec/syntax.md
In the 'reserved-statement' nonterminal, there is an ambiguity if there is more than one whitespace character between the 'reserved-keyword' and the first non-whitespace character of the 'reserved-body', because these whitespace characters can be seen as part of the 's' nonterminal or as part of the 'reserved-body' nonterminal.
According to the principles explained in #725 and the proposed resolution of #721, it is not desired that a 'reserved-body' starts with a whitespace character; rather, such a whitespace character is meant to be interpreted as part of the preceding 's' nonterminal.
Test case:
```
.regex   /foo/{xyz}{{hello}}
```
This patch removes this ambiguity, by disallowing whitespace as the first character of a 'reserved-body' in a reserved-statement.
It thus fixes the first …
=> Disallow whitespace as the first character of a reserved-body in a reserved-statement.

spec/formatting.md, spec/syntax.md
Closes #748
Adds a clarifying note about `.match` not acting as a declaration and updates misleading examples.
=> Clarify that .match selectors are not declarations

spec/registry.md
@catamorphism identified this as a gap in e.g. #739. 
This PR defines what a non-negative integer option value is for `:number` and `:integer`. It does not attempt to address the larger question raised in 738/739.
=> Define non-negative integer option

spec/formatting.md, spec/syntax.md
Closes #749.
See #716 for context.
=> Clarify that options and attributes are unordered

test/README.md, test/data-model-errors.json
While modifying ICU4C tests to read JSON directly from the test files in this repo, I noticed that the data-model-errors.json file I'd previously contributed is not actually valid JSON. 
Added braces to make it valid, and updated README file accordingly.
=> Change format of test/data-model-errors.json file

spec/registry.dtd, spec/registry.xml
Add comments to make clear that the DTD and XML forms of the default registry are not part of the tech preview, but that comments are welcome.
Note that we still need to do #596
=> Remove registry.dtd and registry.xml from Tech Preview

test/test-functions.json
Fixes #662 
Add tests for invalid number literals as required by the default registry.
=> Tests for invalid number literals

test/README.md, test/test-functions.json
Per discussion on #759 , this PR removes expected output for `:date`, `:time`, and `:datetime`, except for error cases (since fallback handling is part of the spec).
Also added a note in the README to explain that.
I didn't remove the expected output for `:number`/`:integer` test cases, since that seems less likely to vary? But perhaps that should be done as well.
=> Remove expected output from date/time formatter tests

docs/tools/linkify.js
This wasn't done in time for the LDML45 release, but capturing it publicly for later implementation. Can be added to the `tr35-messageformat.html` file.
=> Linkify the specification

exploration/bidi-usability.md
Addresses #746.
Provide a design for bidi isolation of MFv2 _syntax_ elements, allowing users and tools to provide messages in right-to-left languages that look normal or have minimal disruption from the Unicode Bidirectional Algorithm.
This design does not require the use of isolates or markers, so it is still possible to create messages that look funky.
This design ignores the UAX31 whitespace definition requirements addressed by #673. Note that the design provided here is more closely tailored to ensure isolate sequences, once opened, are closed and that they tightly wrap only the things desired. There is some funkiness around `name` that we might improve (see the doc).
=> [DESIGN] Bidi usability

exploration/expression-attributes.md
While working on [moz.l10n](https://github.com/mozilla/moz-l10n/), a new Python localization library that uses the MF2 message and [resource data model](https://github.com/eemeli/message-resource-wg/pull/16) to represent messages from a number of different current syntaxes, I've come across at least the following use cases for [expression attributes](https://github.com/unicode-org/message-format-wg/blob/main/exploration/expression-attributes.md):
- In addition to supporting a limited set of HTML elements, Android String Resources may use `<xliff:g>` to wrap [nontranslatable content](https://developer.android.com/guide/topics/resources/localization#mark-message-parts). This is best represented in MF2 with a `@translate=no` attribute.
- Web extension `messages.json` files allow for named …
=> Add use case for `source` expression attribute

spec/errors.md
Fixes #763 
The "MAY" statement being replaced is untestable and, indeed, is inconsistent with some of the MUSTard that occurs later.
=> Remove inappropriate normative statement from errors

spec/errors.md
As initially observed at https://github.com/unicode-org/message-format-wg/pull/774#discussion_r1578160893
=> Avoid presumptive use of "always"

spec/registry.md
As discussed during today's call, we should communicate more clearly that using undefined options may allow for writing currently-errorfree messages that later turn into errors.
=> Add note about updates adding options causing errors

spec/syntax.md
During publication of v45, I found that we were missing a number of terms that we actively use in the specification. Among these are:
- variable
- external variable
- local variable
This PR defines those terms.
=> Define missing definitions for variables

exploration/selection-declaration.md
Fixes #736, Works on #747 
This design document describes the effect of selectors on subsequent pattern placeholders of the same operand. It presents several alternatives.
This is still in "DRAFT" form and not yet ready for the WG as a whole.
=> [DESIGN] Effect of selectors on placeholders

exploration/bidi-usability.md
Drop the `bidi` rule, and allow `name` to be LR/RL/FS -isolated.
Allow an LRI immediately after a non-content newline.
Relax expression & markup isolation to not require pairing on a syntactic level, as the LRI can also be terminated by a newline.
=> Simplify source bidi isolation rules

spec/message.abnf, spec/syntax.md
Currently, we are very strict about which characters may be escaped, and where. This means that in the syntax we have https://github.com/unicode-org/message-format-wg/blob/6d7b4ba213e686ff2d403d3025d38d76b42b75f7/spec/message.abnf#L103-L105
As discussed in #635 and during the 2024-03-18 call, this could be simplified by allowing each of the characters `\`, `{`, `|`, `}` to be escaped in all the positions we allow for any of them to be escaped. Doing so would simplify the syntax, make escaping easier to understand for users, and simplify implementations.
This relaxation would come with the small cost of making the messages `this|that` and `this\|that` synonymous, much like we already allow for `hello` and `{{hello}}` to be synonymous.
This PR is not intended for consideration for the LDML …
=> Collapse all escape sequence rules into one

spec/syntax.md
As [discussed](https://github.com/unicode-org/message-format-wg/blob/main/meetings/2024/notes-2024-05-13.md#743) on yesterday's call, we should instruct processors to only escape as necessary.
This adds a new normative SHOULD for "when programmatically emitting message syntax", which is novel for the spec.
=> Recommend not escaping all the things

exploration/code-mode-introducer.md, exploration/exact-match-selector-options.md, exploration/quoted-literals.md, exploration/selection-matching-options.md, exploration/string-selection-formatting.md, exploration/variable-mutability.md, exploration/variants.md
This PR updates the status of various design docs and otherwise fixes minor issues (mainly that the title wasn't set). It also adds notes to non-standard docs kept for historical purposes.
=> Update design docs and their status

exploration/function-composition-part-1.md
This design doc partially addresses #515. It covers some of the same ground as the design doc in #645, but should be seen as a prequel to #645.
Before getting into solutions, I thought it would be useful to collect together some examples and questions, omitting the  last two sections from the design doc template.
This document is also an attempt to summarize the ICU-TC mailing list discussion that included @macchiati, @markusicu, @echeran and @richgillam . (Some of the comments, which fall more under "proposed solutions", will be included in a future sequel to this design doc.) 
My goal is to get this document into a state that everyone can agree on before finishing part 2 (with the proposed solutions).
I invited some reviewers on an "in case you're interested" basis.
=> Add design doc on function composition

exploration/function-composition-part-1.md
@macchiati suggested using names for models instead of "model 1" and "model 2". This introduces "the simple model" and "the preservation model".
=> Simplify terms in function-composition-part-1 design doc

spec/message.abnf
Fixes #720 
The `name` production matches NCName except that we exclude U+FFFD. This updates the comment in the ABNF.
=> Fix comment about `name`

spec/data-model/README.md, spec/data-model/message.json
Closes #716
As discussed in the parent issue and its other follow-up #751, the order of options and attributes should not matter for their formatting or other processing. Reflecting this in the data model by making these use a mapping makes it clearer that e.g. `{:foo one=13 two=42}` and `{:foo two=42 one=13}` should be considered equivalent.
Note, though, that the order isn't completely lost here. The TS data model uses an ordered `Map` for these, and numerous JSON processors provide guarantees about retaining the order, even though the JSON spec does not require that. So making this change does not in practice make it harder for message syntax serialisers to retain the order that options or attributes may have had originally.
=> Use mappings for data model options and attributes

docs/why_mf_next.md
Rendered markdown output before (highlight added):
After:
=> Docs: fix confusing formatting in `why_mf_next.md`

exploration/data-driven-tests.md
This PR updates the testing design document to capture the decisions and conversation around testing since November.
The main updates are:
- Update suggestions around test format to explain the rationale for JSON.
- Describing the test schema.
- Referencing test functions.
- Removing example tests from the document because we have test files in the repo that illustrate usage.
=> Update 'Data-driven tests' design document

exploration/bidi-usability.md
Simplifies LRM/RLM/ALM usage in options and attributes by allowing them after literals (note that unquoted literals cannot include these characters and that quoted literals are enclosed in quotes.
=> Tweak `bidi` in options/attributes

exploration/number-selection.md
While reading through the [Selection on Numerical Values](https://github.com/unicode-org/message-format-wg/blob/main/exploration/number-selection.md) document I noticed a couple of example English ordinal categories were misrepresented.
=> Fix references to English ordinal categories

spec/message.abnf, spec/syntax.md, test/tests/syntax.json
Fix for a part of #809, CC @lucacasonato
When parsing a complex message, we should be lenient about trailing whitespace, and silently ignore it. It has no meaning, and should not be considered an error.
None of the parser complexity concerns around leading whitespace apply here.
=> Allow trailing whitespace for complex messages

test/tests/functions/number.json, test/tests/syntax.json
Discovered while updating the JS implementation to use the official test suite.
=> Apply minor test fixes

exploration/default-registry-and-mf1-compatibility.md, spec/registry.md
I can't remember why/how we ended up with `short` being the default value for the `:datetime` `dateStyle` and `timeStyle`, and their `:time` and `:date` equivalents. Given how dates and times tend to be placed within text, I think that while `short` is a good default for time, `long` is better for dates.
In a JS en-US environment, we get:
`short`
- 7/1/24
- 4:20 PM
- 7/1/24, 4:20 PM
`medium`
- Jul 1, 2024
- 4:20:00 PM
- Jul 1, 2024, 4:20:00 PM
`long`
- July 1, 2024
- 4:20:00 PM GMT+3
- July 1, 2024, at 4:20:00 PM GMT+3
So the overall default for `:datetime` would be `dateStyle=long timeStyle=short`:
- July 1, 2024 at 4:20 PM
=> Default to medium rather than short dateStyle

spec/data-model/README.md, spec/formatting.md, spec/message.abnf, spec/syntax.md
Given that we also have `quoted-char` and `quoted-pattern`, it is somewhat confusing to have a bare `quoted` rule. It would be much clearer to call it `quoted-literal`, and correspondingly specify that `unquoted` is `unquoted-literal`.
Doing so would also fix at least two places in the formatting text which already include references to _quoted literal_ as a named thing.
=> Rename `quoted` as `quoted-literal` and `unquoted` as `unquoted-literal`

exploration/selection-declaration.md
The labels for mutable and immutable are backwards. This fixes that.
=> [DESIGN] [FAST-TRACK] Fix the titles of two design options to match their contents

exploration/error-handling.md
Add design doc to contextualize the PR #795 based on the issue & discussion begun in #782 .
=> Add design doc for error handling

test/README.md
Update README for tests directory to include a table relating error names in the test schema to error names in the spec.
=> Add table of errors to test README (#706)

test/tests/syntax-errors.json, test/tests/syntax.json
Beginning to address #843 and the corresponding item under https://github.com/unicode-org/message-format-wg/wiki/Things-That-Need-Doing .
I tried to test each variation of each rule (up to but not including `identifier`.) I didn't try to test combinations of variations. For example, for this rule:
```
complex-message   = *(declaration [s]) complex-body [s]
```
the idea would be to add tests that exercise the following four (partial) derivations:
```
complex-message -> complex-body
complex-message -> complex-body s
complex-message -> declaration complex-body
complex-message -> declaration s complex-body
```
This isn't exhaustive by any means, but it was broad enough that I found one bug in the ICU4J parser (the `".input{$x}{{}}` test case) and two bugs in the ICU4C parser (the `\\\\` test …
=> Add more exhaustive syntax tests (#843)

spec/formatting.md
Fixes #857 
Thanks to @mvilks for noticing.
=> Fix typo in example

spec/message.abnf, spec/syntax.md, test/tests/syntax.json
Closes #610 
Closes #809 
Closes #848 
Closes #849 
CC @lucacasonato
As agreed in the balloting under #848, complex messages should be allowed to start with whitespace.
=> Allow whitespace at complex-message start

spec/errors.md, spec/syntax.md, test/schemas/v0/tests.schema.json, test/tests/data-model-errors.json
See #847 for context and discussion.
This does not address the questions about identifier normalization also raised in the parent issue; that should be done in a separate PR.
=> Add Duplicate Variant error

exploration/bidi-usability.md
This PR contains the design document for bidi handling at the syntax level. It contains a fairly comprehensive description of the problem space with examples.
=> [DESIGN] Implement changes to bidi to permit non-strict formation

exploration/expression-attributes.md, spec/data-model/README.md, spec/data-model/message.dtd, spec/data-model/message.json, spec/formatting.md, spec/syntax.md
Closes #642 
Following the acceptance of the "Expression Attributes" design yesterday, this notes that approval in the doc, and updates the _attributes_ accordingly so that they have no runtime impact.
A separate PR adding contextual `u:` options will follow.
=> Accept attributes design & remove spec note

test/README.md
PR #853 should've included this, as PR #850 was merged while it was open, adding the table.
Asking for fast-tracking this editorial PR.
=> Add Duplicate Variant to table in test/README.md

exploration/selection-declaration.md
As discussed in this week's call, I'd like to add a new alternative to the design doc. My own preferences as expressed in #824 have not changed, but this is a viable candidate for consideration.
=> Add new selection-declaration alternative: Require annotation of selector variables in placeholders

spec/README.md
Based on discussion in the 2024-07-22 call and in PR #829, update the stability policy.
=> Update the stability policy

spec/errors.md, spec/formatting.md
Updates to the spec that implement the design doc introduced in #804.
Filed initially as a draft pending the [previously discussed](https://github.com/unicode-org/message-format-wg/blob/main/meetings/2024/notes-2024-06-24.md#804) updates to the design doc, but happy to accept reviews and recommendations for the text already.
=> Refine error handling text

exploration/selection-declaration.md
This design doc was first proposed back in March, and we should finally start discussing which of its options to choose.
I think the problem originally presented in #736 is real, and not well served by our current syntax. Of the options we've identified in the [design document](https://github.com/unicode-org/message-format-wg/blob/accept-selection-declarations/exploration/selection-declaration.md), using variables instead of expressions in `.match` statements seems like the only one that would simplify rather than complicate our syntax and runtime behaviour, as it removes rather than adds to what we already have.
=> Select "Match on variables instead of expressions" for selection-declarations

exploration/selection-declaration.md
I believe this example mistakenly used `.input` instead of `.match` before its selectors
=> Fix "Allow immutable input declarative selectors" example

exploration/bidi-usability.md
The design I actually think we should adopt is the "hybrid approaches" one. This is a necessary first step on the highway to UAX31 compliance and I think is responsibly contained/managed. It is a hybrid approach, in that it permits testable strict implementations to be created (particularly for message serialization).
=> [DESIGN] Update bidi design document to show proposed design

test/tests/data-model-errors.json, test/tests/syntax-errors.json, test/tests/syntax.json
A few things noticed while updating my implementation:
- Some of the new syntax tests were missing expected errors (in particular, bad-selector) beyond the first.
- An unsupported-statement error has an incorrect expected-parts value
- We should test that declaration-like content in quoted patterns is fine, and that `*` and `|*|` are distinguished for duplicate-variant errors.
=> Miscellaneous test fixes

CONTRIBUTING.md, README.md
This PR is intended to work in tandem with @srl295's PR #875 
- change the contributing page to point to Unicode's contributing page
- change the contributing page to point to the README.md file for joining instructions
- change the README.md to include joining instructions consistent with Unicode's actual policy. Previously we just asked people to join our mailing list and watch the repo. That's good for _following_ the work.
=> Update contributing and joining info

spec/errors.md, spec/formatting.md, spec/syntax.md
This PR is seeking to fulfill the following [Things That Need Doing](https://github.com/unicode-org/message-format-wg/wiki/Things-That-Need-Doing#error-handling):
- Ensure that a complete enumeration and error types is in place (also discussed on [2024-07-22](https://github.com/unicode-org/message-format-wg/blob/main/meetings/2024/notes-2024-07-22.md#topic-result-of-balloting-for-error-handling-830))
- Ensure that error requirements are defined in the specification
- Ensure that error fallback format is defined for each error state
After a somewhat thorough review, the changes needed for the above are mostly but not completely editorial, adding explicit references, moving text around, removing unnecessary MUSTard, and making better use of our _well-formed_ and _valid_ definitions.
The one …
=> Clarify error & fallback handling

spec/registry.md
Fixes #868 
This adds normative SHOULD language to using CLDR plural and ordinal data, which was intended originally.
- clarifies that keyword selection follows exact match
- clarifies the purpose of rule-based selection
- makes non-CLDR-based implementation permitted
=> Clarify rule selection

exploration/maintaining-registry.md
Capture for discussion the general ideas for how to organize the registry in the post-45 time period.
Notably, @sffc [mentioned number skeletons](https://github.com/unicode-org/message-format-wg/pull/621#discussion_r1482260505) in a comment on #621:
> Note: My original idea from 5 years ago was that MF would use number skeletons and then become the specification that defines number skeletons since they are currently specified only in the ICU documentation.
This goaded me to write down some of the concepts floating around in my head about how to manage the registry going forwards.
=> [DESIGN] Maintaining the Standard, Optional and Unicode Namespace Function Sets

spec/formatting.md
The upcoming work to implement resolved value might make this patch unnecessary or obsolete, but fixing the typo (missing `{`/`}` around the variable in the pattern) just in case
=> Fix a typo in an example

spec/formatting.md, spec/message.abnf, spec/syntax.md
Adds the bidi strong marks ALM, RLM, and LRM plus the bidi isolate controls LRI, RLI, FSI, and PDI to the syntax.
Formally defines optional vs. non-optional whitespace.
Non-optional whitespace must include at least one whitespace character. Optional whitespace may contain only bidi marks (which are invisible).
This replaces PR#673. This fixes #661, #847.
TODO: Add guidance on "strict" bidi.
=> Add bidi support and address UAX31/UTS55 requirements

spec/registry.md
=> Specify `bad-option` for bad digit size option values

spec/formatting.md, spec/syntax.md
This change defines equality as discussed in the 2024-09-09 teleconference in the following ways:
- It defines _name_ equality as being under NFC
- It defines _literal_ equality as explicitly **not** under NFC
- It moves _name_ before _identifier_ in that section of text to avoid a forward definition.
Note that this deviates from discussion in 2024-09-09's call in that we didn't discuss literals at length. It also doesn't discuss non-name/non-literal values, which I'll point out are limited to ASCII sequences such as keywords.
=> Address name and literal equality

spec/message.abnf
Fixes #893
See discussion there.
=> Fix attribute value to be literal

spec/registry.md
A continuation for #798 and #814, defining the composition behaviour for numerical values.
=> Define function composition for :number and :integer values

spec/registry.md
This fixes the issue identified in https://github.com/unicode-org/message-format-wg/pull/904#discussion_r1796571267: We should require matching keys to a non-normalized compare value, as we do normalize the key values. Without this change, using a non-normalized `key` and `compare` value would not match even if they hold the exact same sequence of code points.
I also modified & moved the note, as it bears calling out that formatting a `:string` doesn't do normalization.
=> Apply NFC normalization during :string key comparison

test/tests/bidi.json
=> Add tests for changes due to bidi/whitespace

test/tests/functions/integer.json
In the WG meeting today, @eemeli gave a reminder that the operand of an `:integer` resolved value is an integer. This test checks for that.
=> Add test for :integer and :number composition

spec/registry.md
I noticed that `:integer` does not include the "never" value for the option `useGrouping`. This is a bug.
=> Fix `:integer` option `useGrouping` values

spec/syntax.md
This was added in #692 and modified in #884. I'm relatively confident that we do not intend to introduce additional restrictions or requirements for managing bidi text during the tech preview.
=> Drop syntax note on additional bidi changes

test/tests/functions/string.json, test/tests/syntax.json
=> Add tests for changes due to #885 (name/literal equality)

spec/data-model/README.md
This note was added in #668, and we've discussed it on and off since then. My sense is that the data model is easier to work with and less error-prone if the namespace is kept as a part of the name.
=> Drop data model request for feedback on "name"

spec/appendices.md, spec/message.abnf, spec/syntax.md
The goal was to allow surrogates in localizable content, but not in names or anything else that is "code".
This change reflects that agreement.
=> Allow surrogates in content, issue #895

spec/formatting.md
This addresses concerns raised in #903 
- define `option resolution` as a term
- require that option order is not significant
I was tempted to define the term `resolved options`, but held back.
=> Define "option resolution" and require order to be insignificant

spec/message.abnf, spec/syntax.md
`complex-body` was already always prefixed by optional space, so in that case there was effectively two subsequent optional spaces: that is unnecessary. It is much cleaner to remove the optional leading space from the `quoted-pattern` definition, and instead move it to explicitly before `quoted-pattern` in  `variant`.
This change is purely editorial and has no normative impact.
=> Clean up `quoted-pattern` definition

spec/formatting.md
=> Clarify note about eager vs. lazy evaluation

README.md
I thought it would be useful to add this external link.
=> Add a link to messageformat.dev to the README file

test/schemas/v0/tests.schema.json, test/tests/bidi.json, test/tests/functions/date.json, test/tests/functions/datetime.json, test/tests/functions/integer.json, test/tests/functions/number.json, test/tests/functions/string.json, test/tests/functions/time.json, test/tests/syntax.json, test/tests/u-options.json
The current tests do not account for the [bidirectional isolation](https://github.com/unicode-org/message-format-wg/blob/main/spec/formatting.md#handling-bidirectional-text) of the formatted results. This adds an option `bidiIsolation` to the tests, with values `'default'` and `'none'` corresponding to the _Default BiDi Strategy_ and to a strategy of not applying any isolation.
Most of the existing tests follow the `'none'` strategy, and have been left unchanged except for noting this state of affairs. The `bidi.json` tests have been updated to use the `'default'` strategy, as that seemed appropriate.
A new `type: 'bidiIsolation'` part is added, and included in the `u-options.json` `expParts` results as appropriate; some bugs in those tests have also been addressed.
=> Fix tests for bidirectional isolation

spec/formatting.md
When implementing bidi isolation, it took me a while to figure out that the _function context_ directionality should not default to the message directionality, but be left empty unless overridden by `u:dir`.
To see how this works, consider this English message:
```
Hello {$name :string} 1234
```
If we were to use the message's LTR directionality when formatting the placeholder, and if the name were RTL, we would end up with a _resolved value_ that claimed that its contents were LTR, when they actually are not. The placeholder would therefore not be isolated, and the message would render incorrectly (i.e. with `1234` to the left of the name).
If instead we don't have any presumptions about the directionality of the `$name`, then we end up either auto-detecting its direction within the …
=> Do not initialise function context direction from message direction

spec/registry.md
As we've now defined _resolved value_ as a term, and e.g. formatting refers to "resolving" placeholders, we should replace/expand the "Composition" sections of default function descriptions with "Resolved Value" sections.
This should help provide a clearer basis for the text around `:number offset` proposed in #926, which is currently proposing two alternative _resolved value_ definitions for `:number`.
=> Replace Composition with Resolved Value sections for default functions

spec/errors.md, spec/registry.md
See #924 for the origin of this PR.
=> Provide normative guidance on function/option/option value impl.

spec/registry.md
Initial implementation of the `:currency` function.
This function will be **standard** in 2.0.
Note behavior differences from `:number` and `:integer`.
`:unit` is in #922.
=> Implement `:currency` function in the default registry

spec/registry.md
Remove a note that is no longer relevant
=> Remove tech preview note from `:string`

spec/README.md
Fixes #928 
Explicitly reserves the `u:` namespace, which was previously only mentioned in the syntax.
Limits spec option values to `a-zA-Z0-9`, `-` and `.`. The `.` is not currently used, but is needed to allow for e.g. `2.5` as a future reserved value.
Replaces two "MUST NOT" restrictions elsewhere with "will not" to match the style of the rest of the text.
=> Limit spec-defined option values

spec/registry.md, test/tests/functions/math.json
Fixes #701.
An alternative to #926.
Adds `:math` as a new numeric function that can `add` or `subtract` from the operand.
Note that the option values are more strict than for other functions; option values beyond "digit size option" are considered errors.
=> Add a :math function, for addition and subtraction

spec/registry.md, test/tests/functions/integer.json
More explicitly defines numeric matching for when it's well-defined, and when it's not well-defined.
Leaves values beyond non-negative integers as implementation-defined, and replaces the JSON reference with the `digit-size-option` ABNF rule, as it's a better fit.
=> Define matching for simple integers, leave others up to implementations

spec/formatting.md, test/tests/fallback.json, test/tests/functions/number.json
This is a continuation for the changes of #728, defining a _fallback value_ explicitly as a _resolved value_, and rephrasing the parts of the spec that refer to resolution failures to instead test for whether a _resolved value_ is a _fallback value_.
=> Fix fallback value definition and use

spec/registry.md
Let's not embarrass ourselves, eh? 
The trailing selector should use the keyword `one` instead of the exact match `1`, in part because other languages need to explode (or contract, e.g. in languages such as `ja` or `zh`) the matrix.
=> Internationalize the `:math` example

spec/registry.md
In [this thread](https://github.com/unicode-org/message-format-wg/pull/911#discussion_r1845265757) on #911, @macchiati and I discussed the handling of implementation-defined literal values and implementation-defined types.
This change splits the "MAY _accept_" for these two cases, permitting both and saving us having to say "... or an implementation-defined value..." in lots of places.
=> Address "implementation-defined" literal and type values

spec/formatting.md, spec/u-namespace.md, test/tests/u-options.json
See #916 for some of the preceding discussion.
In addition to changing the directionality of a placeholder, we should treat an explicitly set `u:dir` option as a request to isolate the placeholder, even if the direction matches the message's direction.
This requires a small change to our default bidi strategy.
The inheritance of the option is not specified when it's set on a value that's used as a function operand, so e.g. a message like
```
.local $world = {world :string u:dir=ltr}
{{hello {$world :string}}}
```
might or might not have the placeholder isolated (depending on the implementation), while it would always be isolated in messages like
```
hello {world :string u:dir=ltr}
```
and
```
.local $world = {world :string u:dir=ltr}
{{hello {$world}}}
```
=> Always apply isolation when `u:dir` is set

spec/README.md
Fixes #930 
Also clarifies that [!IMPORANT] blocks are normative.
=> Linkify stability policy

test/tests/functions/number.json
When an option value does not match the required option values, function behaviour is left as implementation-defined. Therefore, we should not specify an expected formatted result for them.
=> Drop exp value for :number tests with bad option values

spec/registry.md
This is the part of the changes originally proposed in #911 that was deemed as immediately mergeable on today's call.
Perhaps a little pre-emptively, it adopts the nomenclature to be introduced in #946.
This PR is expected to be followed up with separate PRs for the RECOMMENDED override options.
=> Add hour12 date/time override option

spec/formatting.md
We have one instance of a normative note. This fixes it.
=> Fix normative-in-informative

exploration/maintaining-registry.md, spec/registry.md
=> Change standard/optional to required/recommended

spec/registry.md
This is as per the discussion in the WG, separating them out from https://github.com/unicode-org/message-format-wg/pull/911
Two changes from that:
1. Used RECOMMENDED instead of Optional, as per https://github.com/unicode-org/message-format-wg/pull/946
2. I noticed also there that RECOMMENDED needs a maturity status, so added a placeholder for that, with **Proposed**. Since that is only in exploration/maintaining-registry.md, I presume it would be removed for release.
=> Add calendar and numberingSystem options to date/time

spec/registry.md
This still has the ABNF for time zone ID, which should disappear as soon as I can replace it with something formal.
It's fair game to discuss whether this should be RECOMMENDED instead.
=> Create option `timezone` as Proposed REQUIRED option

spec/registry.md
This introduces `:unit` as an optional function, per discussion elsewhere.
=> Implement `:unit` as Proposed RECOMMENDED in the registry

spec/README.md, spec/appendices.md, spec/data-model/README.md, spec/errors.md, spec/formatting.md, spec/intro.md, spec/syntax.md
This PR updates the specification for conversion to the LDML 46.1 release (and future maintenance).
The titles of the various documents have been updated to match the TOC (mostly by removing "MessageFormat 2.0" from every page and by removing "DRAFT". (An exception to removing MF2 from the title is the data-model, where it's in a sub-directory and could be considered the formal title of the thing??)
One mention of Tech Preview was replaced with Final Candidate.
The TOC was moved to the intro. The readme was made non-normative and excluded from the specification.
=> Update specification and readme for "Final Candidate"

spec/errors.md, spec/formatting.md, spec/syntax.md
Given that our spec includes this: https://github.com/unicode-org/message-format-wg/blob/7c1f1a4af4aead387ca6aec48fffc2c6e2191c4d/spec/registry.md?plain=1#L33-L34
We should apply that same guideline to our own examples which use non-default functions.
=> Add namespaces to example non-default functions

spec/formatting.md
I'm submitting this PR to test my understanding of the spec. As I understand it (having read https://github.com/unicode-org/message-format-wg/issues/918 ), the directionality of `fmt` _could_ be determined by introspection on `fmt`, but the implementation is not required to do that introspection. Rather, the resolved value of the expression has both an "input directionality" (determined by the `u:dir` attribute) and an "output directionality" (determined by the function handler for the annotation, or with a default value for placeholders without annotation.) The "output directionality" is what is meant by "the directionality of `fmt`" in the original text. 
I was confused because point 5 of  https://github.com/unicode-org/message-format-wg/issues/918 implies that no introspection is …
=> Clarification to default bidi strategy

spec/data-model/message.json
While putting together some Python tooling for MF2 (mozilla/moz-l10n#40), I came across a few bugs in the JSON Schema that had been missed, as it looks like no-one's actually used it for realz previously. This PR is meant to only fix those bugs, and not change the intent of the schema in any way.
The tooling in question isn't a Python formatter implementation, but bidirectional converters between a number of formats (including the MF2 source & JSON interchange formats) and the `moz.l10n` internal message data model (which is very closesly based on MF2, but designed for developer ergonomics rather than interchange).
=> Fix data model JSON Schema

spec/functions/string.md
Fixes #979 
Previously this was a NOTE. Making it IMPORTANT gives it normative force. The alternative would be to remove the 2119 keyword and just make it advice.
=> Make normalization advice in `:string` normative

spec/functions/number.md
This option value was introduced in #915, and was specifically discussed at least under https://github.com/unicode-org/message-format-wg/pull/915#discussion_r1831635432 and during some of our weekly calls. After its introduction, I submitted a [TC39 proposal](https://github.com/tc39/proposal-intl-currency-display-choices) for the option value, which is now at Stage 2.
However, further discussions of the proposal in TC39 TG2, (tc39/ecma402#643 and at the [last meeting](https://github.com/tc39/ecma402/blob/main/meetings/notes-2025-01-16.md#currency-display)) have identified the current data to be quite limited, as `<symbol alt="formal">`is _only_ used for TWD in zh-Hant in all of CLDR.
The more useful form of this that's proposed in the TC39 proposal would e.g. allow for the symbol string …
=> Drop :currency currencyDisplay=formalSymbol option value

spec/functions/number.md
This is a purely editorial change that should be fast-tracked: the exact same section was included under both `:number` and `:integer`, and it makes more sense under "Number Selection". It should also be referenced in all the places where the default value of `select` is set.
=> Deduplicate the section "Default Value of `select` Option"

spec/functions/number.md, test/tests/functions/currency.json
As discussed today, we should leave out selection from `:currency` and `:unit` for now, as it's not clear that data is available to select correct plural values for them. For example, consider how the English phrase "$3 is your total price" refers to the currency value in the singular.
If/once selection on these values is better defined, we should consider adding support for that in MF2.
Where necessary, plural selection on the numerical values of currencies and unitized values is still possible via `:number` and `:integer`, which do support selection.
=> Drop selection from :currency and :unit

exploration/default-registry-and-mf1-compatibility.md, exploration/number-selection.md, spec/functions/README.md, spec/functions/datetime.md, spec/functions/number.md, spec/u-namespace.md
- cldr-smoke version of tr35 should not be referred to or linked to, ever.
See also:
- https://github.com/unicode-org/cldr/pull/4353
- https://unicode-org.atlassian.net/browse/CLDR-18295 (broken MFv2 spec links)
=> spec: fix bad links to cldr-smoke

spec/syntax.md
As identified in #995, the key comparison text should be specified to talk about _literal_ keys, rather than all keys, as that's a bit misleading: Catch-all `*` keys are never compared to selector values, and they have only one source representation.
=> Add missing "literal" specifier for key equality

spec/message.abnf, spec/syntax.md
With the simplifications we've made to the syntax, in particular allowing unpaired surrogates and dropping the unsupported constructs, the character definitions are no longer benefiting from building on a common `content-char` definition, and it's simpler to not refer to it.
This change is purely editorial, as the final meaning of the ABNF stays just the same as before.
=> Simplify syntax character definitions, dropping content-char

spec/functions/number.md
Fixes #956 
A separate `:percent` function is added, and the `style` option dropped from `:number` and `:integer`.
As proposed in #987, selection is not enabled for `:percent`.
I've also left out the `notation` and `compactDisplay` options, as I'm not aware of any actual use cases combining them with percent formatting.
=> Remove `style=percent` from :number and :integer

spec/functions/datetime.md, spec/functions/number.md, spec/message.abnf, spec/syntax.md, test/tests/functions/datetime.json, test/tests/functions/integer.json, test/tests/functions/number.json, test/tests/syntax.json
Fixes #724 
As discussed today, our `name` definition is a slightly restricted variant of the XML `NCName`, which has not been updated to account for developments in the last 15 years or so that have e.g. included combining marks and the ALM in the `name-start` range.
So as the `name` production is already messy, `unquoted-literal` is not really made _much worse_ by allowing `name-char` as its first character. Doing so also allows us to drop the `number-literal` rule from the syntax.
The `number-literal` rule is still needed for number functions, hence its re-definition in the Number Operands section. Note that I've left out the exponenetial part from it, as the `+` character is no longer valid without quoting.
This change also removes the need to quote `2-digit`, a valid literal value …
=> Allow name-char as first character of unquoted-literal

spec/syntax.md
This addresses the problem by spelling out the difference between `|*|` and `*` in keys.
=> Add a note about representing the string `*` in a key

spec/formatting.md, spec/functions/README.md, spec/functions/datetime.md, spec/functions/number.md, spec/intro.md, spec/syntax.md
As discussed previously (most recently in https://github.com/unicode-org/message-format-wg/pull/974#discussion_r1894125386), we should update our terminology to no longer refer to a "function registry", a term that we don't actually define.
This PR applies that change, along with some incidental cleanup. The term _**default function**_ is introduced, and used where appropriate.
The GitHub label `registry` should probably also be renamed as `default-functions`.
=> Drop references to a "function registry"

spec/message.abnf, spec/syntax.md
https://github.com/unicode-org/message-format-wg/issues/724 Rationalize name-char
=> Rationalize name-char

spec/functions/number.md, test/tests/functions/integer.json, test/tests/functions/number.json
For context, see #1006 
As pointed out by @aphillips in a comment on the ICU4X-TC feedback doc:
> [It's] nearly impossible to localize a message in which [the `select`] option is passed by reference, since tools and translators can't tell how to translate the messages or how to explode (expand/contract) the list of keywords in a given locale.
We can't really make using a variable for `select` a syntax or data model error unless we add a really special case for it in the Syntax part, but this is _nearly_ that.
Note that as shown in the test cases, formatting the following message would result in `bad-option` and `bad-selector` errors:
```
.local $sel = {1 :number select=exact}
.local $bad = {$sel :number}
.match $bad
1 {{ONE}}
* {{operand select {$bad}}}
```
=> Require select option to be set by a literal value

spec/formatting.md, spec/functions/README.md, spec/functions/datetime.md, spec/functions/number.md
This fixes some of the issues identified in the ICU4X TC in the doc linked from https://github.com/unicode-org/message-format-wg/issues/1006#issuecomment-2659730990 by removing the notation, compactDisplay, and numberingSystem options from all functions that currently have them.
This is not a complete solution, nor is it the one preferred by the ICU4X TC, but for at least these options it's the simplest thing we can do, and as @aphillips notes in a comment on the doc:
> Compact display strikes me as a candidate for removal to another function, since not all platforms have this feature in their low-level I18N libraries. We hived off percent. Compact display seems more optional.
The removal of `notation` and `compactDisplay` was previously considered in #664, but dismissed on …
=> Drop the notation, compactDisplay, & numberingSystem options

spec/intro.md, spec/syntax.md
I found two notes with normative language; this fixes one to be IMPORTANT instead (and removes the character range comment, as we've since added namespaces that should be used), and drops the unnecessary phrase from the other.
=> Fix normative language in notes

spec/u-namespace.md
This clarifies the requirement status for each `u:` option separately, as `u:id` only has an effect if the output can be something other than a single string, and concerns have been raised about `u:locale`.
I would be very happy to say that `u:id` and `u:dir` MUST be supported, if the rest of the WG agrees.
This should also clarify that an implementation might choose to support a subset of the `u:` options.
=> Define optionality separately for each u: option

spec/appendices.md, spec/data-model/README.md, spec/errors.md, spec/formatting.md, spec/functions/README.md, spec/functions/datetime.md, spec/functions/number.md, spec/intro.md, spec/syntax.md, spec/u-namespace.md
This PR includes the changes necessary to prepare the specification for LDML47, which is the first Stable release of MF2.
Normative changes:
- Activate the stability policy
Non-normative changes:
- Fix header indentation to support ToC generation
- Disambiguate headers where necessary
Fixes #1001
=> Preparing the specification for LDML47 release

spec/functions/README.md, spec/intro.md
With the specification of `u:locale`'s Draft status in #1012, we're now using those terms outside the Default Functions section. Correspondingly, it would probably be better to define them in the Stability Policy so it's clear what they mean for `u:locale` as well.
This PR only moves the text to a different location, hence marking it as editorial & askign for fast-tracking.
=> Move note about Draft vs. Stable status to Stability Policy

spec/formatting.md
On today's call, we decided to merge #1016, and to add text to the main part of the spec clarifying the need to carry the information about an option value's origin in its _resolved value_. That information is here added in three places:
- The _resolved value_ definition, with a normative MUST requirement.
- The _resolved value_ example.
- The _option resolution_ algorithm.
=> Include explicit text on literal option origin

spec/formatting.md
PR #1019 was merged without this small correction from https://github.com/unicode-org/message-format-wg/pull/1019#discussion_r1960404598, which should be included.
=> Add missing suggestion from #1019

spec/formatting.md, spec/functions/datetime.md, spec/functions/number.md, spec/syntax.md
Fix errors in term highlighting. The missing terms are:
- annotation (not fixed, no longer used formally in the spec)
- bad-option-error (fixed here)
- error  (not fixed)
- expression-resolution (fixed here)
- field-option (fixed here)
- formatter (not fixed)
- function-resolution (fixed here)
- literal-resolution (fixed here)
- namespace (fixed here)
- option-value (not fixed)
- style-option (fixed here)
- variable-resolution (fixed here)
- whitespace (not fixed)
=> Fix term link errors

spec/formatting.md
=> Clarify option literalness details

spec/syntax.md
See https://github.com/unicode-org/message-format-wg/issues/1030
=> Text consistency

spec/errors.md, spec/formatting.md, spec/functions/README.md, spec/functions/datetime.md, spec/functions/number.md, spec/functions/string.md, spec/intro.md, spec/syntax.md, spec/u-namespace.md
Fixes #1034
Mostly the changes are straightforward and completely editorial, though I did opt to make a few further changes as I went:
- Defining also _digit size option_, which we effectively already use as a term
- Some of the explanatory text about `:number select` added in #1027 is moved from Resolved Values to Number Selection
- Harmonize the introductions to each function's options and make sure that each required option is indeed REQUIRED.
I left out a definition of _resolved options_ that I think we probably ought to add as well, but thought that the above could be done as a first step.
=> Define _option value_ and _digit size option_

spec/intro.md
Fixes (part of) ~~#1024.~~ #1033 
@macchiati Demonstrated that the stability policy could logically conflict with locally-assigned default-namespace functions or options. This fixes the policy to allow us to assign **_new_** values that conflict with such.
I believe the change is consistent with working group consensus.
=> Allow valid message invalidation with new default functions

spec/syntax.md
See https://github.com/unicode-org/message-format-wg/issues/1028
=> Literal keys contents / values

spec/intro.md, spec/syntax.md
Moves these definitions from the stability policy into the section on identifiers in syntax.
=> Define reserved and custom identifiers

test/tests/functions/integer.json, test/tests/functions/number.json
Unless I'm misunderstanding something, `literal select {1 :integer select=exact}` should format to `literal select 1` (with no fallback output), since `exact` is a literal.
=> Tests: fix 'literal select' tests for :number and :integer

test/README.md, test/tests/fallback.json
[The spec for `:test:function` says](https://github.com/unicode-org/message-format-wg/blob/main/test/README.md#test-functions):
"If `FailsFormat` is true, attempting to format the _placeholder_ to any formatting target will fail."
This doesn't say anything about what the output should be for `:test:function fails=format` with any operand. However, the first two tests in fallback.json impose requirements on the output. This is stronger than what the spec requires. Hence I suggest removing these tests.
=> Clarify meaning of `fails` option for test functions

README.md
Update our front-door/status page to reflect the release of MF2 as stable.
=> Post-47 front door

spec/syntax.md
Fixes #1029
Removed unnecessary literal quotes from examples and ensured that there was also an option that required pipes so both were visible. Did not add any notes to explain this.
=> Fix markup examples to show that literals work normally

spec/formatting.md
=> Clarify option resolution regarding fallback option values

test/tests/functions/integer.json, test/tests/functions/number.json
The changes in #1046 weren't quite enough, as they don't account for this part of the spec: https://github.com/unicode-org/message-format-wg/blob/662076e128887cad9caa5502b4d4601c5c9bb231/spec/functions/number.md?plain=1#L645
That means that the formatting of a placeholder with `select=$bad` does not experience fallback, even if an error is emitted.
=> Fix select tests to not presume fallback for formatting

test/schemas/v0/tests.schema.json, test/tests/syntax.json, test/tests/u-options.json
The test suite `expParts` should not expect message text parts to be formatted as `"literal"`, but as `"text"`. The current type is misleading, given that in our spec _literals_ are a different thing.
=> In tests, use "text" rather than "literal" as the type for formatted-parts text parts

.github/workflows/validate_tests.yml, test/schemas/v0/tests.schema.json, test/tests/bidi.json, test/tests/data-model-errors.json, test/tests/fallback.json, test/tests/functions/currency.json, test/tests/functions/date.json, test/tests/functions/datetime.json, test/tests/functions/integer.json, test/tests/functions/math.json, test/tests/functions/number.json, test/tests/functions/string.json, test/tests/functions/time.json, test/tests/pattern-selection.json, test/tests/syntax-errors.json, test/tests/syntax.json, test/tests/u-options.json
While reviewing the messageformat.dev documentation, I started to re-think the `source` value that's currently included in formatted parts.
I think we should drop it, as it makes a part of what ought to be considered implementation details into a public API (such as the name of a message variable or function). If a user does have a need to identify a specific part in the output, that ought to be explicit, and it's what we have `u:id` for.
For markup in particular it adds no value, as the `source` value is constructable from the `name` and the `kind`.
CC @ryzokuken
=> In test suite, drop source from non-fallback formatted parts

test/README.md, test/schemas/v0/tests.schema.json, test/tests/u-options.json
After #1012, the `u:locale` option has Draft status, while `u:id` and `u:dir` are RECOMMENDED. However, the tests for all three are in the same file, and indistinguishable from eahc other.
~We should for now drop the rather minimal tests for `u:locale`, and add more comprehensive tests when the status changes.~
See latest comments, as the PR now keeps the tests, but adds an array of tags to them.
=> Add test tags, initially for u: options

spec/formatting.md
Fix #997 
The working group resolved that in v48 we would make the Default Bidi Isolation Strategy not just required but also the default.
=> Make the Default Bidi Strategy required and default

README.md, spec/README.md, spec/appendices.md, spec/data-model/README.md, spec/functions/datetime.md, spec/intro.md, test/schemas/v0/tests.schema.json
Rebranding the specification as _Unicode MessageFormat_ in the wake of v47's stable release.
Fixes #1058
=> Rebranding to Unicode MessageFormat

test/tests/bidi.json
These were formerly correct or contained typos
=> Fix some test descriptions

spec/functions/number.md
Fixes #960 
Per the discussion in the 2025-04-14 telecon, allow digit size options to be to clamped to an implementation-specific value.
=> Allow clamping of digit size options

spec/functions/number.md
In the 2025-05-12 teleconference, the group agreed to make the name of this function less generic. A number of alternative names were proposed in the call. The name `:offset` was used here, partially as a placeholder while we seek consensus.
We agreed that the new function would be limited to adjusting the value of the operand by small integer values. _Digit Size Option_, used here, would make that from `0` to `999`. It has been proposed that this be restricted to `1` to `99`.
In this pull request, note that I added the function name to subsections. The current spec doesn't link properly to subsections because all functions use the same section ID. I did not change the other functions to match, pending discussion.
Fixes #959
=> Change `:math` to `:offset` and remove draft status

spec/formatting.md
I was re-reading the `MessageValue` example and noticed that it's easy to skip over what the last three methods are for, so I added a reference to the earlier text.
I also thought that the `getValue()` method could have another name, since it's confusing to think about the "value" that it returns, vs. the enclosing `MessageValue`. The name I thought of was `getResult()`, but I'm open to other suggestions. I also thought it needed a little more explanation.
=> Clarifications to 'Resolved Values' section

test/tests/functions/offset.json
=> Rename :math tests as :offset tests

spec/formatting.md
Previously, this stated that markup resolution MUST always succeed. However, resolution of `u:` options can fail, so that wasn't true.
=> Fix contradiction in markup resolution

exploration/percent-format.md
This document now includes the proposed design discussed in the (poorly documented, sparsely attended) 2025-05-19 call. The emerging consensus appears to be:
- `:number`/`:integer` with option `style=percent` (this is the current design) with scaling
- `:unit` with unit `percent` is REQUIRED but other units are not required, this function has NO scaling
The most recent commit posits that `:number`/`:integer` select _after_ scaling because we don't support fraction selection currently.
> [!NOTE]
> All previous conversations were marked resolved on purpose and not because their content was in any way deficient, off topic, or necessarily addressed. Please comment on the proposed design.
=> Design document for percent formatting

spec/functions/datetime.md
This is proposed as a separate change from #1077, as it was not discussed on the call.
The intent with the text updated here is to clarify what happens when the `timeZone` option is set on a date/time function.
The SHOULD/MAY language that's proposed is intended to allow for an implementation that does not support time zone conversions, which I believe matches the case in JS Temporal.
Is there prior art of `local` being used as a time zone value as we're proposing, or are there alternatives that other date/time formatters use?
=> Define time zone values and conversions

exploration/semantic-skeletons.md
This design document contains the proposed design for including semantic skeletons into Unicode MessageFormat's functions.
This PR is based on @sffc's [doc](https://docs.google.com/document/d/1s7GeN5V0cnw9B1erfMHTWwmnxz0EJkq2v78ZjzRq2t8/edit)
=> Semantic skeletons design

exploration/README.md, exploration/dataflow-composability.md
Per #1090, mark the doc as obsolete and add "obsolete" to the README as a possible status.
=> Mark dataflow-composability design doc as obsolete
