README.md, guidelines/chair-group.md
Closes #67 
Draft for chair group "rules" and "definition" [source document](https://docs.google.com/document/d/1U6PiFopoOqPyAgJ_KSzEfZOyKIcCGA-qqb_PyRrv_Mc/edit?ts=5e5dd569)
=> docs: chair-group initial commit

guidelines/chair-group-members.md
=> Add Chair Group list

guidelines/chair-group-members.md
Collecting names of more people who volunteered for chair group to the list.
@DavidFatDavidF @nbouvrette
Anyone else who wants to volunteer can use this PR for convenience and add themselves.
@zbraniecki @stasm
=> Add more volunteers to chair group

guidelines/decision-process.md
Strawman of the decision making process to be discussed in the wg monthly meeting on 20th April 2020
=> Draft decision process

meetings/2020/notes-2020-05-18.md
=> Added May 18th meeting notes.

docs/glossary-and-resources.md
Please take a look.
Everyone can consider themselves a reviewer.  Add comments (or approval) and we can discuss here.
@romulocintra @DavidFatDavidF @nbouvrette @zbraniecki @stasm @jamuhl @aphillips @sffc @mihnita @mimckenna @dchiba @ghroten @srl295 @jrwats @longlho
=> Add terminology to glossary and convert from wiki page to repo file

delegates.md, meetings/2019/notes-2019-11-25.md, meetings/2019/notes-2019-12-16.md, meetings/2020/notes-2020-01-06.md, meetings/2020/notes-2020-01-27.md, meetings/2020/notes-2020-02-24.md, meetings/2020/notes-2020-03-23.md, meetings/2020/notes-2020-04-20.md, meetings/2020/notes-2020-05-18.md, meetings/2020/notes-2020-06-15.md, meetings/2020/notes-2020-07-20.md
Please rename my three-letter-long acronym to `STA`.
=> Replace SMY → STA

meetings/2020/notes-2020-09-21.md Create notes-2020-09-17.md
=> Create notes-2020-09-21.md 

meetings/task-force/#103-2020-08-31.md
=> Create task force -  #103-2020-08-31.md

exploration/variants.md
A few examples of copy for #93.
=> Add examples of copy which requires variants

spec/message.ebnf, spec/syntax.md
This PR adds [`spec/syntax.md`](https://github.com/unicode-org/message-format-wg/blob/syntax-proposal/spec/syntax.md) as a starting point for our MF2 grammar considerations. This document is based on the syntax specification prepared earlier by @stasm and represents an evolution of the "A" option presented in #229, taking into account comments and other responses to the presentation.
Given the time constraints, not all comments have been taken into account. We are not suggesting that this is a final syntax, but a sufficiently minimal compromise on which further changes may be applied.
Compared to the "A" option, the following changes have been made:
- All message-internal comments are removed.
- Unicode escapes are removed.
- "Plain" messages are added. These allow for the representation …
=> Add syntax proposal with EBNF

spec/syntax.md
=> Update markup element example to updated syntax

spec/syntax.md
Closes #268
Text and Literal are very tolerant because a container format with its own
escape sequences is expected in common use.
This was prompted by post-meeting discussion with @echeran and @mihnita.
=> Explain the liberal Text and Literal contents

spec/formatting.md
Builds on #304, which should be merged before this.
Closes #297
This PR does not attempt to provide exhaustive contents for variable resolution, but at least a start that should correspond to the consensus reached (so far) in issue #297. It also clarifies the precedence of local vs. external variables, on which we've had some discussion, but I'm not able to find a corresponding issue.
CC @macchiati, who I wasn't able to add directly as a reviewer.
=> Add variable resolution

guidelines/contributing-to-agenda.md, meetings/2023/notes-2023-01-23.md, meetings/agenda.md
=> Notes from 2023-01-23

spec/formatting.md, spec/message.abnf, spec/syntax.md
=> Change the literal delimiter to the vertical pipe character.

spec/message.abnf, spec/syntax.md
This is a follow-up to #359, in which I changed the docs and the escape sequence productions, only to forget to edit the delimiters themselves...
=> Actually change literal delimiters

exploration/selection-matching-options.md
Replacing the previous PR, which got tangled up with other changes on my fork. We need this doc for discussion.
=> Provide selection matching options (best vs. first match)

docs/goals.md
In our teleconference of 2023-04-24 we discussed our goals and the status of our deliverables for the fall 2023 release. These edits attempt to embody that discussion.
=> Update goals.md per 2023-04-24 teleconference

spec/message.abnf, spec/syntax.md
=> Fix typo in ABNF rule for function

docs/consensus_decisions.md
As discussed on Monday's call. For background, see [this presentation](https://docs.google.com/presentation/d/19Q90N6Z9HNF0t_bc2_jtUdYu2PKTPy1oFxuJsxrh2O8/edit?usp=sharing).
=> Add consensus decision on formatting function context

spec/formatting.md
Closes #28
Proposing here effectively the same solution as discussed in the issue.
CC @aharon-lanin, @rxaviers, @macchiati who've commented on the issue but I'm not able to add as a reviewer.
=> Add Bidirectional Isolation section to formatting

exploration/0002-expression-attributes.md
This should've been included earlier. Thank you @stasm for noticing. Requesting fast-tracking.
=> Add missing "Status: Proposed" to expression attributes design doc

README.md, spec/formatting.md, spec/message.abnf, spec/registry.md, spec/syntax.md
Following the 2023-10-23 teleconference, implement "option 2a with additional ugliness".
=> Implement text-mode-first syntax

exploration/syntax-exploration-2.md
Syntax Exploration v2 refines options from the Beauty Contest, and should therefore link to that page.
=> Link to history in syntax-exploration-2.md

exploration/data-driven-tests.md
A design document to gain consensus on the MF2 test suite, both content and runner.
=> Data-driven tests proposal

exploration/code-mode-introducer.md
This design doc attempts to capture the options for beautifying the code mode introducer.
=> (Design) Code Mode Introducer choice

exploration/delimiting-variant-patterns.md
Updating doc after balloting finished with a conclusion.
=> Update status of Delimiting of Patterns in Complex Messages design doc

spec/message.abnf, spec/syntax.md
=> Implement ideographic space

README.md, docs/goals.md
Updates the repo README to use only `LDML45` functions/features. It doesn't list everything possible with a message.
Also update the copyright date. @srl295 Copying you in case I shouldn't do that or you have other guidance.
=> Update README.md for use in announcements.

spec/message.abnf
Fixes #600 
As we lock down the ABNF, start to fix spacing and alignment. In this PR all of the changes are editorial.
Note that I have moved a few of the productions in an attempt to organize items more logically. I have also added comments for individual blocks.
=> Beautify the ABNF

spec/syntax.md
Follow up to #614.
I also notice some of the beautification from #613 didn't land here so maybe you have other plans to update these code blocks to match, but I didn't bother trying to apply any of them as they *should be* only decorative and I didn't know if you wanted them in an unrelated PR. This change fixing an actual syntax problem needs updating even if the formatting changes aren't urgent to touchup.
=> Port ABNF fix to relevant mention in syntax document

spec/data-model/README.md
Fixes #638
- Clarifies the purpose of the data model
- Clarifies the normative requirements of the data model
- Adds some examples of required and optional capabilities
=> Clarify the data model introduction

spec/README.md
=> Remove expression attributes from stability policy

exploration/default-registry-and-mf1-compatibility.md
This is per the 2024-02-14 teleconference.
=> Implement changes to date/time functions

spec/syntax.md
Closes #641
As discussed during the Tuesday 13 Feb call.
=> Add tech preview attribute recommendation

test/test-functions.json
Removes a questionable test.
Fixes #726.
=> Fix #726: remove :time/:datetime compose test

spec/appendices.md
Create the acknowledgements section. Addresses #711. See that issue for how this was created (although it is self-describing).
Additional names are welcome! Specific acknowledgements for specific deeds are also welcome (as mentioned in the 2024-03-18 call). No omission is intentional. Don't feel shy about putting your name on our work.
=> Create ack section

docs/tech-preview-blog-post.md
Ready for review. Still a little long.
=> Tech Preview Blog Post

meetings/2024/notes-2024-04-29.md
Filing as a PR, as I don't have the rights to push directly on `main`.
=> Add notes for 2024-04-29

meetings/2024/notes-2024-04-29.md
I didn't have time to update our meeting notes immediately after the meeting, but there was important discussion that wasn't captured since I was speaking & taking notes at the same time. Written to the best of my memory of the salient points.
=> Add omitted notes to 2024-04-29 meeting notes

README.md
Maintaining the list of normative changes during tech preview.
=> Update readme with list of normative changes during TP

exploration/expression-attributes.md
Add user-stories and examples to the expression attributes design.
=> [DESIGN] Add user stories / build-out of the expression attributes

test/tests/functions/number.json
=> Remove duplicate test cases in number.json

test/tests/data-model-errors.json
=> Fix typos in data-model-errors tests

spec/registry.md
Addresses #887 
Non-normative changes to the notes specifically part of LDML46
=> Update note on exact numeric match for v46

test/tests/functions/currency.json
These probably should've been a part of #915.
=> Add tests for :currency

.github/ISSUE_TEMPLATE/tech-preview-feedback.md
As identified during yesterday's call.
=> Fix release name in Preview-Feedback issue template

test/tests/functions/string.json
=> Remove coercion from :string tests

spec/functions/datetime.md, spec/functions/number.md, spec/functions/string.md, spec/syntax.md
This PR incorporates additional fixes to #1001 found when assembling the "pour over" version of the specification for v47.
=> Final preparations for v47 pourover

spec/formatting.md
Fixes #1031
Removes the request for feedback.
=> Remove note about Final Candidate
